### ISSUE TITLE
How to handle conditional sampling when using `CustomConstraint`?

### ISSUE THREAD

**Issue by sarahmish** [sdv-dev/SDV#560] opened 2021-08-11 18:46 UTC
### Environment details

* SDV version: 0.11.0
* Python version: 3.7
* Operating System: macOS 10.15.6

### Problem description

Currently when we create a `CustomConstraint` we pass our own functions of `transform` and `reverse_transform`. Depending on how we write these functions, different behaviors can happen. One of them is, the code crashes when we attempt to conditionally sample from the model. The question is, how should we handle conditional sampling and how does it affect how we write the `transform` and `reverse_transform` functions?

### Example

```python3
from sdv.demo import load_tabular_demo
from sdv.constraints import CustomConstraint
from sdv.tabular import GaussianCopula

data = load_tabular_demo()

def transform(table_data, column):
    table_data[column] = table_data[column]
    return table_data

def reverse_transform(table_data, column):
    table_data[column] = table_data[column]
    return table_data

constraint = CustomConstraint(columns=["age"], transform=transform, reverse_transform=reverse_transform)

gc = GaussianCopula(constraints=[constraint])
gc.fit(data)

gc.sample(10, conditions={"contractor": 1.})
```

Then the code crashes because it attempts to access `age` when age is not part of the dataframe
```
KeyError                                  Traceback (most recent call last)
<ipython-input-26-ad98aa9715ab> in <module>
     18 gc.fit(data)
     19 
---> 20 gc.sample(10, conditions={"contractor": 1.})

~/Downloads/SDV/sdv/tabular/base.py in sample(self, num_rows, max_retries, max_rows_multiplier, conditions, float_rtol, graceful_reject_sampling)
    440                 raise ValueError(f'Invalid column name `{column}`')
    441 
--> 442         transformed_conditions = self._metadata.transform(conditions, on_missing_column='drop')
    443         condition_columns = list(conditions.columns)
    444         transformed_columns = list(transformed_conditions.columns)

~/Downloads/SDV/sdv/metadata/table.py in transform(self, data, on_missing_column)
    577 
    578         LOGGER.debug('Transforming constraints for table %s', self.name)
--> 579         data = self._transform_constraints(data, on_missing_column)
    580 
    581         LOGGER.debug('Transforming table %s', self.name)

~/Downloads/SDV/sdv/metadata/table.py in _transform_constraints(self, data, on_missing_column)
    539         for constraint in self._constraints:
    540             try:
--> 541                 data = constraint.transform(data)
    542             except MissingConstraintColumnError:
    543                 if on_missing_column == 'error':

~/Downloads/SDV/sdv/constraints/tabular.py in _run_transform(self, table_data)
     69 
     70     def _run_transform(self, table_data):
---> 71         return self._run(self._transform, table_data)
     72 
     73     def _run_reverse_transform(self, table_data):

~/Downloads/SDV/sdv/constraints/tabular.py in _run(self, function, table_data, reverse)
     59             for column in columns:
     60                 try:
---> 61                     table_data = function(table_data, column)
     62                 except TypeError:
     63                     table_data[column] = function(table_data[column])

<ipython-input-26-ad98aa9715ab> in transform(table_data, column)
      6 
      7 def transform(table_data, column):
----> 8     table_data[column] = table_data[column]
      9     return table_data
     10 

~/opt/anaconda3/envs/sdv/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2904             if self.columns.nlevels > 1:
   2905                 return self._getitem_multilevel(key)
-> 2906             indexer = self.columns.get_loc(key)
   2907             if is_integer(indexer):
   2908                 indexer = [indexer]

~/opt/anaconda3/envs/sdv/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2895                 return self._engine.get_loc(casted_key)
   2896             except KeyError as err:
-> 2897                 raise KeyError(key) from err
   2898 
   2899         if tolerance is not None:

KeyError: 'age'
```

**Comment by linyuehzzz** [comment] 2021-08-29 20:06
I have the same question.

**Comment by npatki** [comment] 2022-01-27 17:50
Thank you for filing this issue with all the great detail! This is a known bug, and I've filed #696 to track it. 

Notes:
- Currently, we use the reject sampling strategy for conditions. This means that we sample entire rows and then filter out any invalid ones based on the condition. It should always be possible to do this (even if there is a `CustomConstraint`). I suspect this bug is caused by some functions being performed done out of order.
- You can manually implement the above logic as a temporary workaround.

I'm closing this issue off in favor of #696 . If you have any follow ups or comments, we can continue to conversation there!

**Closed by npatki** 2022-01-27 17:50 UTC
Labels: question, needs discussion
