### ISSUE TITLE
ValueError when running get_column_pair_plot for single_table in Jupyter Notebook (VSCode)

### ISSUE THREAD

**Issue by PiotrBB** [sdv-dev/SDV#1734] opened 2024-01-08 20:19 UTC
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.8.0
* Python version: 3.10.13
* Operating System: Ubuntu 22.04.3 LTS (WSL on Windows 11)

### Problem description

While following the example available [here](https://docs.sdv.dev/sdv/single-table-data/evaluation/visualization#get_column_pair_plot) I am encountering the following error: `ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed`

```
pip list | grep 'nb\|jup\|plotly\|sdv'
jupyter_client            8.6.0
jupyter_core              5.7.1
jupyterlab-widgets        3.0.9
nbformat                  5.9.2
plotly                    5.18.0
sdv                       1.8.0
widgetsnbextension        4.0.9
```
Code executed:
```
from sdv.single_table import GaussianCopulaSynthesizer
synthesizer = GaussianCopulaSynthesizer(metadata)
synthesizer.fit(input_df)
synthetic_data = synthesizer.sample(num_rows=10_000)

from sdv.evaluation.single_table import get_column_pair_plot

fig = get_column_pair_plot(
    real_data=input_df,
    synthetic_data=synthetic_data,
    metadata=metadata,
    column_names=['timeOnIce', 'hits'],
    )

fig.show()
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[28], line 15
      6 from sdv.evaluation.single_table import get_column_pair_plot
      8 fig = get_column_pair_plot(
      9     real_data=input_df,
     10     synthetic_data=synthetic_data,
     11     metadata=metadata,
     12     column_names=['timeOnIce', 'hits'],
     13     )
---> 15 fig.show()

File ~/project/lib/python3.10/site-packages/plotly/basedatatypes.py:3410, in BaseFigure.show(self, *args, **kwargs)
   3377 """
   3378 Show a figure using either the default renderer(s) or the renderer(s)
   3379 specified by the renderer argument
   (...)
   3406 None
   3407 """
   3408 import plotly.io as pio
-> 3410 return pio.show(self, *args, **kwargs)

File ~/project/lib/python3.10/site-packages/plotly/io/_renderers.py:394, in show(fig, renderer, validate, **kwargs)
    389         raise ValueError(
    390             "Mime type rendering requires ipython but it is not installed"
    391         )
    393     if not nbformat or Version(nbformat.__version__) < Version("4.2.0"):
--> 394         raise ValueError(
    395             "Mime type rendering requires nbformat>=4.2.0 but it is not installed"
    396         )
    398     ipython_display.display(bundle, raw=True)
    400 # external renderers

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed
```

### What I already tried

`pip install --upgrade nbformat`
`pip install --upgrade --force-reinstall -r requirements.txt`
`pip install --upgrade ipykernel`

Charts are outputted to ./iframe_figures, but not displayed in Notebook.

**Comment by npatki** [comment] 2024-01-08 20:47
Hi @PiotrBB, thanks for reaching out and providing the full details. This seems to be an issue with [plotly](https://plotly.com/) -- our graphing library -- and installing its related dependencies. I haven't come across it before. This [StackOverflow Q](https://stackoverflow.com/questions/66557543/valueerror-mime-type-rendering-requires-nbformat-4-2-0-but-it-is-not-installed) seems to heave several answers for it. Maybe you'll find one of them useful?

Other debugging tips:

- Just to sanity check, did you restart the kernel after performing the `pip install` commands?
- Which other libraries are installed in your Python environment? It could be that an external library's dependencies are interfering with your ability to install/upgrade the necessary libraries. To test this for sure, I would recommend:
   - Save the real and synthetic data as CSV files
   - Create a fresh Python environment and _only_ install the latest SDV library in it
   - Within the new environment, load in the CSVs and try to use the visualization. If this succeeds, then the issue is caused by some other library

**Comment by PiotrBB** [comment] 2024-01-09 08:48
Hello @npatki,

Yes, i tried to steps, including kernel restart and still facing same issue.

As per your suggestion, i created fresh python env, installed sdv (and ipykernel) only and rerun the code. I am facing the exact same issue. Here's pip list:
`pip list
Package                  Version
------------------------ ------------
asttokens                2.4.1
boto3                    1.34.15
botocore                 1.34.15
cloudpickle              2.2.1
comm                     0.2.1
contourpy                1.2.0
copulas                  0.9.2
ctgan                    0.8.0
cycler                   0.12.1
debugpy                  1.8.0
decorator                5.1.1
deepecho                 0.5.0
exceptiongroup           1.2.0
executing                2.0.1
Faker                    19.13.0
filelock                 3.13.1
fonttools                4.47.0
fsspec                   2023.12.2
graphviz                 0.20.1
ipykernel                6.28.0
ipython                  8.20.0
jedi                     0.19.1
Jinja2                   3.1.2
jmespath                 1.0.1
joblib                   1.3.2
jupyter_client           8.6.0
jupyter_core             5.7.1
kiwisolver               1.4.5
MarkupSafe               2.1.3
matplotlib               3.8.2
matplotlib-inline        0.1.6
mpmath                   1.3.0
nest-asyncio             1.5.8
networkx                 3.2.1
numpy                    1.26.3
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
packaging                23.2
pandas                   2.1.4
parso                    0.8.3
pexpect                  4.9.0
pillow                   10.2.0
pip                      23.0.1
platformdirs             4.1.0
plotly                   5.18.0
prompt-toolkit           3.0.43
psutil                   5.9.7
ptyprocess               0.7.0
pure-eval                0.2.2
Pygments                 2.17.2
pyparsing                3.1.1
python-dateutil          2.8.2
pytz                     2023.3.post1
pyzmq                    25.1.2
rdt                      1.9.0
s3transfer               0.10.0
scikit-learn             1.3.2
scipy                    1.11.4
sdmetrics                0.13.0
sdv                      1.8.0
setuptools               65.5.0
six                      1.16.0
stack-data               0.6.3
sympy                    1.12
tenacity                 8.2.3
threadpoolctl            3.2.0
torch                    2.1.2
tornado                  6.4
tqdm                     4.66.1
traitlets                5.14.1
triton                   2.1.0
typing_extensions        4.9.0
tzdata                   2023.4
urllib3                  2.0.7
wcwidth                  0.2.13`

**Comment by npatki** [comment] 2024-01-12 18:22
Hi @PiotrBB, thanks for the update. This is a tricky one, as I'm not able to replicate it exactly. But I have a few suggestions for additional tests we can do to pinpoint where exactly the issue is happening.

### Is the issue with plotly?
Try creating a brand new Python environment and only pip installing plotly. Then you can try using the scatter plot function from directly within plotly to see if it works.

From [plotly's demo docs](https://plotly.com/python/line-and-scatter/)

```python
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species",
                 size='petal_length', hover_data=['petal_width'])
fig.show()
```

If this is breaking in your environment, then the issue is within the plotly library, so may be good to search through their GitHub / docs.

### Is it an issue only with scatter plots?
Back in the SDV environment, I wonder if doing a single column plot is also causing any issues?

```python
from sdv.evaluation.single_table import get_column_plot

fig = get_column_plot(
    real_data=df,
    synthetic_data=synthetic_data,
    metadata=metadata,
    column_name='timeOnIce',
    )

fig.show()
```

Let me know what your findings are. We'll be sure to update if we find a way to replicate this or have any other learnings.

**Comment by npatki** [comment] 2024-01-29 21:17
Hi @PiotrBB, I'm classifying this as a bug since it is not intended behavior. Please do let us know if you are able to run the code above to help us pinpoint the issue. We're very interested in discovering any root causes so that we may natively fix this in SDV for you and other users. Thanks.

**Comment by srinify** [comment] 2024-03-29 21:10
Hi @PiotrBB Plotly has a different renderer for Jupyter Notebooks in VSCode which I recommend using instead: https://plotly.com/python/renderers/

You should be able to just tweak your final `fig.show()` code to the following:

```
fig.show(renderer='vscode')
```

Here's a screenshot of it working.

![image](https://github.com/sdv-dev/SDV/assets/801507/1f11ba12-8a5d-4186-862e-d59b770f1c37)

I'm closing out this issue as something for the SDV project to track because the issue lies with other software packages.

**Closed by srinify** 2024-03-29 21:10 UTC
Labels: bug
