### ISSUE TITLE
Categorical Data Question in blog

### ISSUE THREAD

**Issue by SeasonJJ999** [sdv-dev/SDV#1632] opened 2023-10-17 00:33 UTC
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 
* Python version: 3.10
* Operating System: google colab

### Problem description

I read one of our blogs, https://datacebo.com/blog/categorical-data/. It says "Answer = No.  Other columns might be categorical. In our example, the Vendor ID column identifies vendors that help file taxes. We do not want to create entirely new, synthetic vendors — instead, we want to create synthetic taxpayers and assign them to existing vendors. So for our purposes, the Vendor ID column is categorical, because we want to reuse the existing values (along with the patterns that we've learned about them).

This final point is tricky, as your answer may change based on the project. For a different usage, you may want to create new, synthetic vendors. In this case, you'd need to supply a separate Vendor table and mark the Vendor ID as a foreign key reference, instead of categorical.

(Does this concept make sense? The SDV team is still iterating on this particular point, and our understanding may change based on your feedback. Leave us a comment below if you've been confused by ID columns.)"

This No part corresponds to my situation but I do not understand this part. Do I create another table with that column of IDs instead of converting them into categorical data? And link to the original table as a foreign key reference? Can anyone provide some examples of this?

### What I already tried

I tried to find more info in tutorials but did not find any. Also, I checked several posts but not sure if I am having the same issue.

**Comment by npatki** [comment] 2023-10-17 14:47
Hi @SeasonJJ999, nice to meet you and thanks for providing this feedback. If you have any specific examples of the data you are trying to model, it would be great if you could share them with us.

You do not have to create any new tables or do any conversions. The only question the article is trying to answer is: What information should you provide in the metadata? You do not need to modify your original data in any way. For more information about metadata, please see the docs for [single table](https://docs.sdv.dev/sdv/single-table-data/data-preparation) and [multi table](https://docs.sdv.dev/sdv/multi-table-data/data-preparation) usages.

To clarify about th eblog: In the section for **Trap 3**, we have a table with `Vendor ID`. The question is: In the metadata, should this column be specified as an ID column or a categorical column? Options:
1. In a multi table dataset, you may have a separate table corresponding to Vendors. Then `Vendor ID` column is a foreign key to that other, Vendors table. In this case, you would mark the sdtype as `id` in your metadata and add the relationship. The SDV will create brand new vendors, and those new Vendor IDs would show up in the synthetic data.
2. If you do not have another table for Vendors, then you may mark `Vendor ID` as `categorical`. The SDV will then recycle the same Vendor IDs in the synthetic data.

Depending on which option you chose, your metadata will be different. But you do not need to modify the original data.

**Comment by SeasonJJ999** [comment] 2023-10-18 05:05
Hi @npatki Thank you for the clarification. I think I want to the option 2  so I mark those wanted ID columns as categorical in metadata using metadata.update_column(). However, the SDV did not recycle the same IDs in the synthetic data. I am so confused.

**Comment by SeasonJJ999** [comment] 2023-10-18 20:37
Thank you for reply. I have used metadata.to_dict() to check metadata and it was fine.
{'METADATA_SPEC_VERSION': 'SINGLE_TABLE_V1',
 'columns': {'ID': {'sdtype': 'categorical'},
  'WEEK': {'sdtype': 'numerical'},
  'UNITS': {'sdtype': 'categorical'},
  'O': {'sdtype': 'categorical'},
  'DOLLARS': {'sdtype': 'numerical'},
  'KEY': {'sdtype': 'categorical'},
  'C': {'sdtype': 'categorical'}}}
So I have four columns that should be categorical. 
I just tried 3 synthesizers for this, CTGAN, CopulaGAN, and GaussianCopula. But it looks like only GaussianCopula can recycle those same values. I am not sure why.

**Comment by npatki** [comment] 2023-10-18 23:26
Thank you for confirming. Based on the metadata and your description, I am unable to replicate the issue. I see that the IDs from the real data are always being recycled in the synthetic data, as intended (I provided my replication code below).

Is there anything I'm missing? It would be helpful if you could provide the code you're using for training and sampling.

### Replication Code
This is what I tried to test the problem: I created a small dataframe with categorical column `ID` and numerical column `W`. We expect that `'ID'` will contain the values from the real data only.

```python
from sdv.metadata import SingleTableMetadata
from sdv.single_table import CTGANSynthesizer
import pandas as pd

metadata_dict = {
    'METADATA_SPEC_VERSION': 'SINGLE_TABLE_V1',
    'columns': {
        'ID': {'sdtype': 'categorical'},
        'W': {'sdtype': 'numerical'},
    }}
metadata = SingleTableMetadata.load_from_dict(metadata_dict)

data = pd.DataFrame(data={
    'ID': [3009586, 3009586, 3009587, -3009586, -3009586],
    'W': [3009586, 3009586, 3009587, -3009586, -3009587]
})

synth = CTGANSynthesizer(metadata)
synth.fit(data)
synthetic_data = synth.sample(100)
```

From the synthetic data, you can manually verify that only the `ID` values from the real data are present in the synthetic data  (3009586, 3009587, -3009586). However, the the `W` column contains a variety of values since it is numerical.

**Comment by SeasonJJ999** [comment] 2023-10-20 04:27
@npatki Thank you for your reply. But I still encounter the issue. My dataset is a lot bigger. I tried with a subset of 100 rows from the real dataset with 26 unique IDs, it somehow produced fake IDs. And when I tried a subset of 10 rows, it did not produce any fake IDs. Maybe the problem is the size of the dataset? And Sorry I might not be able to provide the code immediately since it has some data that needs to be authorized.

**Comment by npatki** [comment] 2023-10-24 15:22
Hi @SeasonJJ999, interesting. I can replicate your issue with a larger amount of data. This seems like a bug.

I've filed a dedicated bug for it in #1647. I have provided a workaround there that seems to create the correct synthetic data. Take a look and let us know if that works for you.

**Comment by SeasonJJ999** [comment] 2023-10-26 20:49
@npatki Great! Thank you! I saw the bug is solved? Should I reinstall the package to test it?

**Comment by npatki** [comment] 2023-10-27 16:58
Hi @SeasonJJ999 could you link to which bug you see as being solved? At the time I'm writing this comment, I can see that #1647 (linked above) is still open.

**Comment by npatki** [comment] 2023-10-31 15:18
Hi @SeasonJJ999, good news is that the issue has now been resolved. However, you'll have to **wait for the upcoming SDV release** in order to see the updates. The new release will likely be called `1.5.1` or `1.6.0`. 

You can keep an eye out [on our release notes](https://github.com/sdv-dev/SDV/releases) to see when the release is made. Alternatively, you can [clone the SDV GitHub repo](https://github.com/sdv-dev/SDV) directly if you'd like to play around with it now.

I'm closing this issue since the underlying code fix has been discovered and resolved. Let us know if you have any more Qs. Thanks.

**Closed by npatki** 2023-10-31 15:18 UTC
Labels: question, under discussion
