### ISSUE TITLE
I want the ID column length should match the given regex pattern

### ISSUE THREAD

**Issue by Veeresh1996** [sdv-dev/SDV#2229] opened 2024-09-17 13:04 UTC
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.14.0
* Python version: 3.12.3
* Operating System: Windows 11

### Problem description

I am using HMAsynthesizer for Multitables. I am able to generate data with the trained model. But for the columns which I have mentioned as ID's the length of the generated values not matches with the real data even though I have specified the regex pattern. For example, One of the ID column contains 6 digits but the generated output contains some random lengths. **Real Data ID Value:** 300164 **Generated value:** 2690

### What I already tried

This is the metadata for that specific field,
"patnum": {
                    "sdtype": "id",
                    "regex_format": "^\\d{6}$"
                }
Could you please look into it ASAP? Please let me know if you need any other info

Thanks in advance

**Comment by npatki** [comment] 2024-09-17 14:56
Hi @Veeresh1996, SDV is designed to ensure that the synthetic data matches (a) the regex format that you provide _and_  (b) the original data type of the real data. In your case, it seems like the two are in conflict with each other: The regex describes having a 6-digit strings, but it appears to me the original data type is an integer.

The regex may correctly produce strings such as `"002690"` but when converted to an integer, this will become `2690` (no longer 6 characters). So the regex is not really compatible with the data type. To fix this issue, you would have to address root cause of the mismatch.

- You could either update the regex format to ensure that leading 0s are not possible. Eg. Enforce that the first digit cannot be 0: `[1-9]\d{5}` or
- Convert the real data to strings before passing it into SDV so that the synthetic data output will also be strings.

**Comment by Veeresh1996** [comment] 2024-09-17 17:51
Hey Neha, Thanks the solution that you have provided works for me. 
One more question is it possible to generate duplicate values in id columns. For example I want a six digit value with and it is ok to have duplications of the value in same field?

**Comment by npatki** [comment] 2024-09-26 18:40
Hi @srinify and @Veeresh1996, just to clarify something on point 1: When you supply a column as an `id`, it just means that the column represents a label that can help you identify a concept. _It does not always have to be unique._  ([This blog post](https://datacebo.com/blog/categorical-data/) has some useful information.)

As an example, consider three different id columns: 

A. A primary key column might be sdtype id
B. A foreign key column might be sdtype id
C. You may have a generic column that is sdtype id (neither a primary nor foreign key)

In this case, SDV will only enforce that A is unique -- as primary keys must uniquely distinguish every row. SDV will allow B and C to repeat. Just be aware that depending on the regex you provide, it you may need to sample a lot of data in order to see the duplicates. 

@Veeresh1996 Would you like your ID columns (with regex) to be able to repeat at higher frequency? This is definitely a feature request that we can track. We prioritize based on how important it is to your use case, so we would appreciate any more info you are able to provide.

**Comment by srinify** [comment] 2024-10-23 20:55
Hi @Veeresh1996 it's been a while since we've had some activity here on this issue so I'm going to go ahead and close it out. If you have more questions or issues, please feel free to open new GitHub issues :)

**Closed by srinify** 2024-10-23 20:55 UTC
Labels: question, under discussion
