### ISSUE TITLE
Random Primary IDs Regex

### ISSUE THREAD

**Issue by Jo-Lam** [sdv-dev/SDV#1062] opened 2022-10-11 21:56 UTC
### Problem Description

At the moment, regex generate primary ID in ascending order. Should be able to populate that with random order.

### Expected behavior

expect ID are generated in random order/not sorted ascendingly

### Additional context

there are easy solutions out side of sdv

**Comment by Jo-Lam** [comment] 2022-10-11 21:57
https://app.slack.com/client/T017A503B3M/C017G4D8004/thread/C017G4D8004-1665498322.634479
Original Q&A in slack

**Comment by npatki** [comment] 2022-10-12 17:04
Thanks for filling @Jo-Lam. We'll keep this issue open to track interest & communicate progress.

**Workarounds**: You can override the generated primary ID column with random values. For example, if you want to generate unique, random integers between 1000 and 9999 you can do the following:

```python
import random

new_ids = list(range(1000, 10000))
random.shuffle(new_ids)

synthetic_data['ID_COLUMN_NAME'] = new_ids[:len(synthetic_data)]

```

If there are any other workarounds for different use cases, feel free to reply here.

**Comment by ketandaryanani** [comment] 2022-10-14 14:43
Hi, 
I used faker to generate random ID as sting-numeric.
fake = Faker()
fake_ID = [fake.bothify(text= '???#####').upper() for x in range (1000)]
data['Customer_ID'] = pd.DataFrame(fake_ID)

I had similar doubt my column has string-numeric, and when I use primary key on the column, it produces asc. string starting from 'a'...'AA'.. and so on.
Expected was similar pattern of String-numeric combination.
I was not able to use the faker provider bothify and mention (text) pattern I require. The error was 'Generator' object has no attribute.
But my Workaround is as above using faker before passing it through the models

**Comment by npatki** [comment] 2024-04-17 02:45
Closing off as a dupe of #1596 -- which we'll continue to track as a feature request.

**Closed by npatki** 2024-04-17 02:45 UTC
Labels: feature request, feature:sampling
