### ISSUE TITLE
When loading synthesizer from pkl, then trying to synthesizer.sample, I get: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters()

### ISSUE THREAD

**Issue by ryantimjohn** [sdv-dev/SDV#2121] opened 2024-07-11 19:34 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.14.0
* Python version: 3.10.14
* Operating System: Debian GNU/Linux 11 (bullseye)

### Error Description

I have a synthesizer I made previously. I saved it as a .pkl. I loaded the .pkl with `synthesizer = PARSynthesizer.load('synthesizer.pkl')`. Then I ran `synthetic_data = synthesizer.sample(num_sequences=100)`. Now I get this warning:
```py
/opt/conda/lib/python3.10/site-packages/torch/nn/modules/rnn.py:1133: 
UserWarning: RNN module weights are not part of single contiguous
    chunk of memory.
This means they need to be compacted at every call,
    possibly greatly increasing memory usage.
To compact weights again call flatten_parameters().
(Triggered internally at ../aten/src/ATen/native/cudnn/RNN.cpp:1424.)
```
The synthesizer does, in fact, run extremely slowly. What can I do to remedy.

### Steps to reproduce

1. Save a synthesizer.
2. Load it later.
3. Try to create sample data with it.
----------

1. You must have a trained synthesizer named synthesizer before running this:
```
synthesizer.save('synthesizer.pkl')
```

2.
```
synthesizer = PARSynthesizer.load('synthesizer.pkl')
```

3.
```
synthetic_data = synthesizer.sample(num_sequences=100)
```

**Comment by ryantimjohn** [comment] 2024-07-11 20:23
I was able to flatten the parameters by running `synthesizer._model._model.rnn.flatten_parameters()` but this doesn't seem like a good solution

**Comment by srinify** [comment] 2024-07-31 19:30
Hi there @ryantimjohn apologize for the delay here! 

To help me reproduce the issue, I'm curious to know if the trained & saved synthesizers are both using the same version of the SDV or if they're different?

> The synthesizer does, in fact, run extremely slowly. What can I do to remedy.

Approximately how many rows and columns are in each sequence in your training data?

**Comment by srinify** [comment] 2024-08-12 18:18
Hi there @ryantimjohn since it's been a while since I've heard back, I'm going to go ahead and close this issue out. But please feel free to open a new issue with some more context on:

1. If the synthesizers are using same / different versions of SDV?
2. Approx. count of rows / columns in each sequence in your training data.

**Closed by srinify** 2024-08-12 18:18 UTC
Labels: bug, under discussion
