### ISSUE TITLE
Conditional sampling for CTGAN synthesizer not working

### ISSUE THREAD

**Issue by vamsinilla** [sdv-dev/SDV#1424] opened 2023-05-15 09:41 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:1.0.0
* Python version:3.9
* Operating System: Windows

### Error Description
when trying the CTGAN on my original data , and applying conditional sampling for column data. getting the "ValueError: Unable to sample any rows for the given conditions. Try increasing `max_tries_per_batch` (currently: 100). Note that increasing this value will also increase the sampling time.
"

### Steps to reproduce

<Replace this text with a description of the steps that anyone can follow to reproduce the error. If the error happens only on a specific dataset, please consider attaching some example data to the issue so that others can use it to reproduce the error.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment] 2023-05-31 23:19
Hi @vamsinilla, were you able to solve your issue? I'm closing it as a duplicate of #1419. If you are still having problems, feel free to reply and we can reopen the issue to discuss.

**Closed by npatki** 2023-05-31 23:19 UTC
Labels: bug, under discussion
