### ISSUE TITLE
When Run time series model : PAR encounter AttributeError: 'DataFrame' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by CindyQi7788** [sdv-dev/SDV#254] opened 2020-11-21 01:11 UTC
* SDV version: sdv==0.4.6.dev2
* Python version: 3.6.11
* Operating System: AWS SageMaker

### Description

I would like to use PAR model for my data, the columns, such as ['AGE', 'RACE', 'V1'] are inside the DataFrame and they are context_columns = ['AGE', 'RACE', 'V1']

### What I Did

My dataframe contains 
dtypes: dtypes: float64(23), int64(1), object(2)

When I run:

```
from sdv.timeseries import PAR
model = PAR(
    entity_columns=entity_columns,
    context_columns=context_columns,
    sequence_index=sequence_index,
)
model.fit(DATA)
```

```
**Got Error : KeyError: "['AGE', 'RACE', 'V1'] not in index"' **
KeyError                                  Traceback (most recent call last)
<ipython-input-326-17179da5012a> in <module>
      7 )
      8 
----> 9 model.fit(DATA)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sdv/timeseries/base.py in fit(self, timeseries_data)
    201 
    202         if self._entity_columns:
--> 203             self._fit_context_model(transformed)
    204 
    205         LOGGER.debug('Fitting %s model to table %s', self.__class__.__name__, self._metadata.name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sdv/timeseries/base.py in _fit_context_model(self, transformed)
    171         LOGGER.debug('Fitting context model %s', self._context_model.__class__.__name__)
    172         if self._context_columns:
--> 173             context = transformed[self._entity_columns + self._context_columns]
    174         else:
    175             context = transformed[self._entity_columns].copy()

~/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2910             if is_iterator(key):
   2911                 key = list(key)
-> 2912             indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
   2913 
   2914         # take() does not accept boolean indexers

~/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1252             keyarr, indexer, new_indexer = ax._reindex_non_unique(keyarr)
   1253 
-> 1254         self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
   1255         return keyarr, indexer
   1256 

~/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1302             if raise_missing:
   1303                 not_found = list(set(key) - set(ax))
-> 1304                 raise KeyError(f"{not_found} not in index")
   1305 
   1306             # we skip the warning on Categorical

KeyError: "['AGE', 'RACE', 'V1'] not in index"
```

Please let me know why because those columns are the column names in the dataframe.  I don't have a time sequence, but I used the ordered integers as sequence_index.

Thank you very much and Looking forward to your reply.
Xin

**Comment by pvk-developer** [comment] 2021-03-22 12:11
Hi @CindyQi7788 thank you for opening this issue.

Since this issue is old and probably out of date, would you mind trying to reproduce the error with the newest `SDV` release and let us know if the issue can still be reproduced on the newer version.

**Comment by CindyQi7788** [comment] 2021-03-22 12:31
Hi,

Thanks for following up. The project is temporarily closed at our end. If
it resumes, I will test on new version sdv.

Best regards.
Xin

**Comment by pvk-developer** [comment] 2021-03-22 16:00
Thank you for the update @CindyQi7788 , I will close this issue then.
Feel free to reopen it in the future if you end up having the same problem.

**Closed by pvk-developer** 2021-03-22 16:00 UTC
Labels: pending review

**Comment by CindyQi7788** [comment] 2021-03-22 22:04
Thanks, I'll check it out in the future.

Best
Xin
