### ISSUE TITLE
Key error while sampling using trained and saved model

### ISSUE THREAD

**Issue by ObuSama** [sdv-dev/SDV#935] opened 2022-08-03 08:39 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.13.1
* Python version:3.8.8
* Operating System: Windows 10

### Error Description

I have ran and saved a single table user model with the meta file manually updating each data type. No errors were given while running the training and saving. Used HMA1 to train the model. However while sampling and running it is giving a 
key error. I have ran another table and that ran fine. Not able to debug why the error during sampling along. Screenshots attached.

![SDV_error1](https://user-images.githubusercontent.com/30028060/182564053-db82249c-50c5-4828-ad45-65ffa61dba95.jpg)
![SDV_error2](https://user-images.githubusercontent.com/30028060/182564073-4c10966b-cdbe-49fe-9569-5cfe8276f3c1.jpg)

**Comment by DamianUS** [comment] 2022-08-08 21:44
The key error is also being raised when trying to sample from a freshly-trained PAR model in v0.16.0.

I tried both passing the field types metadata and without it, nothing seems to help.

I printed the model metadata just to check if the model inferred properly the data types and everything seems correct.

Here I attach the code used just in case it helps (this is the last version used in which the model infers the field types):

`
import pandas as pd
from sdv.timeseries import PAR
from sdv.metrics.timeseries import TSFClassifierEfficacy

data = pd.read_csv("data/micro_batch_task.csv")
sequence_index = 'start_time'
field_types = {
    "instance_num": {
        "type": "numerical",
        'subtype': 'integer'
    },
    "start_time": {
        "type": "numerical",
        'subtype': 'integer'
    },
    "plan_cpu": {
        "type": "numerical",
        'subtype': 'float'
    },
    "plan_mem": {
        "type": "numerical",
        'subtype': 'float'
    },
    "makespan": {
        "type": "numerical",
        'subtype': 'integer'
    },
}
model = PAR(
    sequence_index=sequence_index,
    segment_size=10,
    epochs=1,
    verbose=True
)
model.fit(data)
print(model.get_metadata().to_dict())
new_data = model.sample(1)
print(new_data)
print(TSFClassifierEfficacy.compute(data, new_data, field_types, target='makespan'))
`

When trying to sample:

`
PARModel(epochs=1, sample_size=1, cuda='cpu', verbose=True) instance created
Epoch 1 | Loss 0.001459105173125863: 100%|██████████| 1/1 [00:51<00:00, 51.42s/it]
{'fields': {'instance_num': {'type': 'numerical', 'subtype': 'float', 'transformer': None}, 'start_time': {'type': 'numerical', 'subtype': 'integer', 'transformer': None}, 'plan_cpu': {'type': 'numerical', 'subtype': 'float', 'transformer': None}, 'plan_mem': {'type': 'numerical', 'subtype': 'float', 'transformer': None}, 'makespan': {'type': 'numerical', 'subtype': 'integer', 'transformer': None}}, 'constraints': [], 'model_kwargs': {}, 'name': None, 'primary_key': None, 'sequence_index': 'start_time', 'entity_columns': [], 'context_columns': []}
100%|██████████| 1/1 [00:00<00:00, 85.72it/s]
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'start_time'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/damianfernandez/PycharmProjects/sdv/main.py", line 46, in <module>
    new_data = model.sample(1)
  File "/opt/homebrew/lib/python3.8/site-packages/sdv/timeseries/base.py", line 268, in sample
    return self._metadata.reverse_transform(sampled)
  File "/opt/homebrew/lib/python3.8/site-packages/sdv/metadata/table.py", line 700, in reverse_transform
    field_data = reversed_data[name]
  File "/opt/homebrew/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/homebrew/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'start_time'

Process finished with exit code 1
`

Maybe I'm not doing something property. I'm new to the library!

**Comment by npatki** [comment] 2022-08-08 23:55
Hi @DamianUS, welcome! Would you be able to file a separate issue with what you're observing? The root cause of the timeseries PAR model is likely different than the initial issue, which uses the multi-table HMA1 model. We can respond separately to your error.

**Comment by ObuSama** [comment] 2022-08-09 09:24
@npatki  I shall try running it in new version. However, tried pip update, didn't work. Could you share the update command to work on jupyter? Wasn't mentioned how to update in the documentation/install section

**Comment by npatki** [comment] 2022-08-11 00:50
Hi @ObuSama, you should be able to use the command below to update the version.

```python
!pip install -U sdv
```

Or to install a specific version
```python
!pip install sdv==0.16.0
```

You may also have to restart the kernel in order to access the latest package.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/3227804/184046945-ed0bac69-4781-41b9-b807-a425a320a8d5.png">

If that doesn't work, it would be helpful if you could share a screenshot or code with what you're trying as well as the error message you are seeing.

**Comment by ObuSama** [comment] 2022-08-11 08:24
@npatki  I have noticed when the there are multiple data types of "id" in the meta data, the models are giving "key error". Is that an issue, where there are multiple fields in a single table of type "id"? When I changed data types and ensured there is only one field with data type "id" it wasn't giving key error.

Also, in the example of relational meta data given in https://sdv.dev/SDV/user_guides/relational/constraints.html  there are multiple fields with type id in the table.

Could you please check on this?

**Comment by npatki** [comment] 2022-08-11 20:06
Hi @ObuSama, the SDV should be able to handle multiple columns with data type "id". Could you share the metadata that's giving you trouble?

**Comment by npatki** [comment] 2022-08-27 19:14
Hi @ObuSama, I'm closing this issue since we've resolved the earlier questions and there hasn't been discussion in a few weeks. If you are continuing to observe any related issues, please respond here and I can reopen the issue. 

If you are experiencing any new problems, feel free to file a new issue and we can take it from there.

**Closed by npatki** 2022-08-27 19:14 UTC
Labels: bug, data:multi-table, under discussion
