### ISSUE TITLE
Argument "conditions" for GaussianCopula forbids sampling

### ISSUE THREAD

**Issue by JetfiRex** [sdv-dev/SDV#374] opened 2021-04-02 06:16 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.8.0 (and now 0.9.0, but not solving the problem)
* Python version: 3.6 (virtual environment)
* Operating System: Windows 10, using jupyter notebook

Others:

* Pycaret version 2.3.0
* Pandas version: 1.1.4
* Numpy version: 1.19.5

### Error Description

I have did this:

```
model = GaussianCopula()
model.fit(real)
synth_data = model.sample(num_rows = 600, max_retries = 300)
```

for some dataframe "real", and it produce this:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-390-212e99ea8040> in <module>
     25     model.fit(real)
     26     # Create 600 rows of data
---> 27     synth_data = model.sample(num_rows = 600, max_retries = 300)
     28 
     29     # Evaluate the synthetic data against the real data

...\.julia\conda\3\envs\py36\lib\site-packages\sdv\tabular\base.py in sample(self, num_rows, max_retries, max_rows_multiplier, conditions, float_rtol)
    365         if conditions is None:
    366             num_rows = num_rows or self._num_rows
--> 367             return self._sample_batch(num_rows, max_retries, max_rows_multiplier)
    368 
    369         # convert conditions to dataframe

...\.julia\conda\3\envs\py36\lib\site-packages\sdv\tabular\base.py in _sample_batch(self, num_rows, max_retries, max_rows_multiplier, conditions, transformed_conditions, float_rtol)
    273         """
    274         sampled, num_valid = self._sample_rows(
--> 275             num_rows, conditions, transformed_conditions, float_rtol)
    276 
    277         counter = 0

...\.julia\conda\3\envs\py36\lib\site-packages\sdv\tabular\base.py in _sample_rows(self, num_rows, conditions, transformed_conditions, float_rtol, previous_rows)
    203         if self._metadata.get_dtypes(ids=False):
    204             if conditions is None:
--> 205                 sampled = self._sample(num_rows)
    206             else:
    207                 try:

...\.julia\conda\3\envs\py36\lib\site-packages\sdv\tabular\copulas.py in _sample(self, num_rows, conditions)
    298                 Sampled data.
    299         """
--> 300         return self._model.sample(num_rows, conditions=conditions)
    301 
    302     def get_likelihood(self, table_data):

...\.julia\conda\3\envs\py36\lib\site-packages\copulas\__init__.py in wrapper(self, *args, **kwargs)
     34     def wrapper(self, *args, **kwargs):
     35         if self.random_seed is None:
---> 36             return function(self, *args, **kwargs)
     37 
     38         else:

TypeError: sample() got an unexpected keyword argument 'conditions'

```
Furthermore, when the `model = GaussianCopula()` changes to `model = CopulaGAN()` it will NOT produce these problems and will successfully sample.

### Steps to reproduce

As before. 
```
model = GaussianCopula()
model.fit(any_pd_dataframe)
model.sample(num_rows = any_number, max_retries= any_number)
```

Update: I tried another dataframe and do exactly as the manual [in the demo](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html) does. This error emerges again.

Update 2: I tried to upgrade the SDV to 0.9.0 and the problem is NOT fixed.

Update 3: use the following code can reproduce directly.
```
import pandas as pd
df = pd.DataFrame([[1, 2, 3],[4, 5, 6], [7,8,9]], columns=['d', 'e', 'f'], index=['a','b','c'])
model = GaussianCopula()
model.fit(df)
model.sample(num_rows = 10)
```

**Comment by pvk-developer** [comment] 2021-04-06 16:45
Hello @JetfiRex I tried to reproduce the error on my end, however I wasn't able to do so.

At first sight it seems that you may be using some older version of copulas, however, would you mind reporting the output of a `pip freeze` command in here?

**Comment by JetfiRex** [comment] 2021-04-06 16:47
Yes. The `pip freeze` command outputs
```
alembic==1.4.1
asn1crypto==0.24.0
attrs==19.3.0
Automat==20.2.0
backcall==0.1.0
baytune==0.4.0
bleach==3.1.0
blis==0.7.4
Boruta==0.3
catalogue==1.0.0
certifi==2019.11.28
cffi==1.11.5
chardet==3.0.4
click==7.1.2
cliff==3.7.0
cloudpickle==1.6.0
cmaes==0.8.2
cmd2==1.5.0
colorama==0.4.3
colorlog==4.7.2
colorlover==0.3.0
conda==4.8.1
conda-package-handling==1.6.0
confuse==1.4.0
constantly==15.1.0
construct==2.10.61
copulas==0.5.0
cryptography==2.8
ctgan==0.4.0
cufflinks==0.17.3
cycler==0.10.0
cymem==2.0.5
Cython==0.29.14
dabl==0.2.0
databricks-cli==0.14.2
dataclasses==0.8
decorator==4.4.1
deepecho==0.1.4
defusedxml==0.6.0
docker==4.4.4
entrypoints==0.3
Faker==4.14.2
Flask==1.1.2
funcy==1.15
future==0.18.2
gensim==3.8.3
gitdb==4.0.5
GitPython==3.1.14
graphviz==0.16
greenlet==1.0.0
htmlmin==0.1.12
hyperlink==21.0.0
idna==2.6
ImageHash==4.2.0
imbalanced-learn==0.8.0
importlib-metadata==3.7.3
incremental==21.3.0
ipykernel==5.1.4
ipython==7.11.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jedi==0.16.0
Jinja2==2.11.3
joblib==1.0.1
jsonschema==3.2.0
julia==0.5.6
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
kiwisolver==1.3.1
kmodes==0.11.0
lightgbm==3.1.1
llvmlite==0.36.0
Mako==1.1.4
MarkupSafe==1.1.1
matplotlib==3.2.1
menuinst==1.4.14
missingno==0.4.2
mistune==0.8.4
mlflow==1.14.1
mlxtend==0.18.0
more-itertools==8.0.2
murmurhash==1.0.5
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.5
nltk==3.5
notebook==6.0.3
numba==0.53.0
numexpr==2.7.3
numpy==1.19.5
optuna==2.6.0
packaging==20.9
pandas==1.1.4
pandas-profiling==2.11.0
pandocfilters==1.4.2
parso==0.6.0
patsy==0.5.1
pbr==5.5.1
phik==0.11.2
pickleshare==0.7.5
Pillow==8.1.2
plac==1.1.3
plotly==4.14.3
ply==3.11
pomegranate==0.14.1
preshed==3.0.5
prettytable==2.1.0
prometheus-client==0.7.1
prometheus-flask-exporter==0.18.1
prompt-toolkit==3.0.3
protobuf==3.15.6
pyasn1==0.4.8
pycaret==2.3.0
pycosat==0.6.3
pycparser==2.18
pycryptodomex==3.10.1
Pygments==2.5.2
pyLDAvis==3.2.2
pynndescent==0.5.2
pyod==0.8.7
pyOpenSSL==18.0.0
pyparsing==2.4.7
pyperclip==1.8.2
pyreadline==2.1
pyrsistent==0.15.7
pysmi==0.3.4
pysnmp==4.4.12
PySocks==1.6.8
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2021.1
PyWavelets==1.1.1
pywin32==223
pywinpty==0.5.7
PyYAML==5.4.1
pyzmq==18.1.0
qtconsole==4.6.0
querystring-parser==1.2.4
rdt==0.4.0
regex==2020.11.13
requests==2.25.1
retrying==1.3.3
ruamel-yaml==0.15.37
scikit-learn==0.24.0
scikit-plot==0.3.7
scipy==1.5.4
sdmetrics==0.2.0
sdv==0.8.0
seaborn==0.11.1
Send2Trash==1.5.0
shap==0.39.0
six==1.11.0
sktime==0.5.3
slicer==0.0.7
smart-open==4.2.0
smmap==3.0.5
spacy==2.3.5
SQLAlchemy==1.4.0
sqlparse==0.4.1
srsly==1.0.5
statsmodels==0.12.2
stevedore==3.3.0
tabulate==0.8.9
tangled-up-in-unicode==0.0.7
tensor==0.3.6
terminado==0.8.3
testpath==0.4.4
text-unidecode==1.3
textblob==0.15.3
thinc==7.4.5
threadpoolctl==2.1.0
torch==1.8.0
torchvision==0.9.0
tornado==6.0.3
tqdm==4.59.0
traitlets==4.3.3
Twisted==21.2.0
twisted-iocpsupport==1.0.1
typing-extensions==3.7.4.3
umap-learn==0.5.1
urllib3==1.22
visions==0.6.0
waitress==2.0.0
wasabi==0.8.2
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.58.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
win-inet-pton==1.0.1
wincertstore==0.2
wordcloud==1.8.1
yellowbrick==1.3.post1
zipp==0.6.0
zope.interface==5.2.0
```

**Comment by JetfiRex** [comment] 2021-04-06 16:48
> Hello @JetfiRex I tried to reproduce the error on my end, however I wasn't able to do so.
> 
> At first sight it seems that you may be using some older version of copulas, however, would you mind reporting the output of a `pip freeze` command in here?

Yes. The `pip freeze` command outputs
```
alembic==1.4.1
asn1crypto==0.24.0
attrs==19.3.0
Automat==20.2.0
backcall==0.1.0
baytune==0.4.0
bleach==3.1.0
blis==0.7.4
Boruta==0.3
catalogue==1.0.0
certifi==2019.11.28
cffi==1.11.5
chardet==3.0.4
click==7.1.2
cliff==3.7.0
cloudpickle==1.6.0
cmaes==0.8.2
cmd2==1.5.0
colorama==0.4.3
colorlog==4.7.2
colorlover==0.3.0
conda==4.8.1
conda-package-handling==1.6.0
confuse==1.4.0
constantly==15.1.0
construct==2.10.61
copulas==0.5.0
cryptography==2.8
ctgan==0.4.0
cufflinks==0.17.3
cycler==0.10.0
cymem==2.0.5
Cython==0.29.14
dabl==0.2.0
databricks-cli==0.14.2
dataclasses==0.8
decorator==4.4.1
deepecho==0.1.4
defusedxml==0.6.0
docker==4.4.4
entrypoints==0.3
Faker==4.14.2
Flask==1.1.2
funcy==1.15
future==0.18.2
gensim==3.8.3
gitdb==4.0.5
GitPython==3.1.14
graphviz==0.16
greenlet==1.0.0
htmlmin==0.1.12
hyperlink==21.0.0
idna==2.6
ImageHash==4.2.0
imbalanced-learn==0.8.0
importlib-metadata==3.7.3
incremental==21.3.0
ipykernel==5.1.4
ipython==7.11.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jedi==0.16.0
Jinja2==2.11.3
joblib==1.0.1
jsonschema==3.2.0
julia==0.5.6
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
kiwisolver==1.3.1
kmodes==0.11.0
lightgbm==3.1.1
llvmlite==0.36.0
Mako==1.1.4
MarkupSafe==1.1.1
matplotlib==3.2.1
menuinst==1.4.14
missingno==0.4.2
mistune==0.8.4
mlflow==1.14.1
mlxtend==0.18.0
more-itertools==8.0.2
murmurhash==1.0.5
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.5
nltk==3.5
notebook==6.0.3
numba==0.53.0
numexpr==2.7.3
numpy==1.19.5
optuna==2.6.0
packaging==20.9
pandas==1.1.4
pandas-profiling==2.11.0
pandocfilters==1.4.2
parso==0.6.0
patsy==0.5.1
pbr==5.5.1
phik==0.11.2
pickleshare==0.7.5
Pillow==8.1.2
plac==1.1.3
plotly==4.14.3
ply==3.11
pomegranate==0.14.1
preshed==3.0.5
prettytable==2.1.0
prometheus-client==0.7.1
prometheus-flask-exporter==0.18.1
prompt-toolkit==3.0.3
protobuf==3.15.6
pyasn1==0.4.8
pycaret==2.3.0
pycosat==0.6.3
pycparser==2.18
pycryptodomex==3.10.1
Pygments==2.5.2
pyLDAvis==3.2.2
pynndescent==0.5.2
pyod==0.8.7
pyOpenSSL==18.0.0
pyparsing==2.4.7
pyperclip==1.8.2
pyreadline==2.1
pyrsistent==0.15.7
pysmi==0.3.4
pysnmp==4.4.12
PySocks==1.6.8
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2021.1
PyWavelets==1.1.1
pywin32==223
pywinpty==0.5.7
PyYAML==5.4.1
pyzmq==18.1.0
qtconsole==4.6.0
querystring-parser==1.2.4
rdt==0.4.0
regex==2020.11.13
requests==2.25.1
retrying==1.3.3
ruamel-yaml==0.15.37
scikit-learn==0.24.0
scikit-plot==0.3.7
scipy==1.5.4
sdmetrics==0.2.0
sdv==0.8.0
seaborn==0.11.1
Send2Trash==1.5.0
shap==0.39.0
six==1.11.0
sktime==0.5.3
slicer==0.0.7
smart-open==4.2.0
smmap==3.0.5
spacy==2.3.5
SQLAlchemy==1.4.0
sqlparse==0.4.1
srsly==1.0.5
statsmodels==0.12.2
stevedore==3.3.0
tabulate==0.8.9
tangled-up-in-unicode==0.0.7
tensor==0.3.6
terminado==0.8.3
testpath==0.4.4
text-unidecode==1.3
textblob==0.15.3
thinc==7.4.5
threadpoolctl==2.1.0
torch==1.8.0
torchvision==0.9.0
tornado==6.0.3
tqdm==4.59.0
traitlets==4.3.3
Twisted==21.2.0
twisted-iocpsupport==1.0.1
typing-extensions==3.7.4.3
umap-learn==0.5.1
urllib3==1.22
visions==0.6.0
waitress==2.0.0
wasabi==0.8.2
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.58.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
win-inet-pton==1.0.1
wincertstore==0.2
wordcloud==1.8.1
yellowbrick==1.3.post1
zipp==0.6.0
zope.interface==5.2.0
```

**Comment by pvk-developer** [comment] 2021-04-06 17:58
@JetfiRex Thank you for your quick response.

This error or bug that you have managed to produce it's due to an older version of `copulas`, more precisely `0.3.2`, which is the one required by `baytune`. I managed to install your environment and run the demo code that you pasted without producing the error (because you have the `copulas==0.5.0`) however if I downgrade it to `0.3.2` i manage to reproduce the error.

```python

In [4]: model.sample(5, max_retries=10)                                                                                                                                                                            
Out[4]: 
   d  e   f
0 -1  0   1
1  5  6   7
2  5  6   7
3  8  9  10
4  5  6   7

In [5]: !pip install copulas==0.3.2                                                                                                                                                                                
Collecting copulas==0.3.2
  Using cached copulas-0.3.2-py2.py3-none-any.whl (46 kB)
ERROR: sdv 0.8.0 has requirement copulas<0.6,>=0.5.0, but you'll have copulas 0.3.2 which is incompatible.
Installing collected packages: copulas
  Attempting uninstall: copulas
    Found existing installation: copulas 0.5.0
    Uninstalling copulas-0.5.0:
      Successfully uninstalled copulas-0.5.0
Successfully installed copulas-0.3.2
WARNING: You are using pip version 20.1; however, version 21.0.1 is available.
You should consider upgrading via the '/home/****/.virtualenvs/test_installs/bin/python -m pip install --upgrade pip' command.

In [6]: model.sample(5, max_retries=10)                                                                                                                                                                            
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a88267b8ad7f> in <module>
----> 1 model.sample(5, max_retries=10)

~/.virtualenvs/test_installs/lib/python3.6/site-packages/sdv/tabular/base.py in sample(self, num_rows, max_retries, max_rows_multiplier, conditions, float_rtol)
    365         if conditions is None:
    366             num_rows = num_rows or self._num_rows
--> 367             return self._sample_batch(num_rows, max_retries, max_rows_multiplier)
    368 
    369         # convert conditions to dataframe

~/.virtualenvs/test_installs/lib/python3.6/site-packages/sdv/tabular/base.py in _sample_batch(self, num_rows, max_retries, max_rows_multiplier, conditions, transformed_conditions, float_rtol)
    273         """
    274         sampled, num_valid = self._sample_rows(
--> 275             num_rows, conditions, transformed_conditions, float_rtol)
    276 
    277         counter = 0

~/.virtualenvs/test_installs/lib/python3.6/site-packages/sdv/tabular/base.py in _sample_rows(self, num_rows, conditions, transformed_conditions, float_rtol, previous_rows)
    203         if self._metadata.get_dtypes(ids=False):
    204             if conditions is None:
--> 205                 sampled = self._sample(num_rows)
    206             else:
    207                 try:

~/.virtualenvs/test_installs/lib/python3.6/site-packages/sdv/tabular/copulas.py in _sample(self, num_rows, conditions)
    298                 Sampled data.
    299         """
--> 300         return self._model.sample(num_rows, conditions=conditions)
    301 
    302     def get_likelihood(self, table_data):

~/.virtualenvs/test_installs/lib/python3.6/site-packages/copulas/__init__.py in wrapper(self, *args, **kwargs)
     34     def wrapper(self, *args, **kwargs):
     35         if self.random_seed is None:
---> 36             return function(self, *args, **kwargs)
     37 
     38         else:

TypeError: sample() got an unexpected keyword argument 'conditions'

In [7]:                                                                                                                                                                                                            
```

I will create a pull request and upgrade the [BTB](https://github.com/MLBazaar/BTB/) copulas version so it can be installed and used with `SDV`. 

I'm closing this issue since an error is already displayed when you are using the wrong version of copulas with `SDV`:
```
ERROR: sdv 0.8.0 has requirement copulas<0.6,>=0.5.0, but you'll have copulas 0.3.2 which is incompatible.
```

**Closed by pvk-developer** 2021-04-06 17:58 UTC
Labels: bug

**Comment by JetfiRex** [comment] 2021-04-06 18:09
> @JetfiRex Thank you for your quick response.
> 
> This error or bug that you have managed to produce it's due to an older version of `copulas`, more precisely `0.3.2`, which is the one required by `baytune`. I managed to install your environment and run the demo code that you pasted without producing the error (because you have the `copulas==0.5.0`) however if I downgrade it to `0.3.2` i manage to reproduce the error.
> 
> ```python
> In [4]: model.sample(5, max_retries=10)                                                                                                                                                                            
> Out[4]: 
>    d  e   f
> 0 -1  0   1
> 1  5  6   7
> 2  5  6   7
> 3  8  9  10
> 4  5  6   7
> 
> In [5]: !pip install copulas==0.3.2                                                                                                                                                                                
> Collecting copulas==0.3.2
>   Using cached copulas-0.3.2-py2.py3-none-any.whl (46 kB)
> ERROR: sdv 0.8.0 has requirement copulas<0.6,>=0.5.0, but you'll have copulas 0.3.2 which is incompatible.
> Installing collected packages: copulas
>   Attempting uninstall: copulas
>     Found existing installation: copulas 0.5.0
>     Uninstalling copulas-0.5.0:
>       Successfully uninstalled copulas-0.5.0
> Successfully installed copulas-0.3.2
> WARNING: You are using pip version 20.1; however, version 21.0.1 is available.
> You should consider upgrading via the '/home/****/.virtualenvs/test_installs/bin/python -m pip install --upgrade pip' command.
> 
> In [6]: model.sample(5, max_retries=10)                                                                                                                                                                            
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-6-a88267b8ad7f> in <module>
> ----> 1 model.sample(5, max_retries=10)
> 
> ~/.virtualenvs/test_installs/lib/python3.6/site-packages/sdv/tabular/base.py in sample(self, num_rows, max_retries, max_rows_multiplier, conditions, float_rtol)
>     365         if conditions is None:
>     366             num_rows = num_rows or self._num_rows
> --> 367             return self._sample_batch(num_rows, max_retries, max_rows_multiplier)
>     368 
>     369         # convert conditions to dataframe
> 
> ~/.virtualenvs/test_installs/lib/python3.6/site-packages/sdv/tabular/base.py in _sample_batch(self, num_rows, max_retries, max_rows_multiplier, conditions, transformed_conditions, float_rtol)
>     273         """
>     274         sampled, num_valid = self._sample_rows(
> --> 275             num_rows, conditions, transformed_conditions, float_rtol)
>     276 
>     277         counter = 0
> 
> ~/.virtualenvs/test_installs/lib/python3.6/site-packages/sdv/tabular/base.py in _sample_rows(self, num_rows, conditions, transformed_conditions, float_rtol, previous_rows)
>     203         if self._metadata.get_dtypes(ids=False):
>     204             if conditions is None:
> --> 205                 sampled = self._sample(num_rows)
>     206             else:
>     207                 try:
> 
> ~/.virtualenvs/test_installs/lib/python3.6/site-packages/sdv/tabular/copulas.py in _sample(self, num_rows, conditions)
>     298                 Sampled data.
>     299         """
> --> 300         return self._model.sample(num_rows, conditions=conditions)
>     301 
>     302     def get_likelihood(self, table_data):
> 
> ~/.virtualenvs/test_installs/lib/python3.6/site-packages/copulas/__init__.py in wrapper(self, *args, **kwargs)
>      34     def wrapper(self, *args, **kwargs):
>      35         if self.random_seed is None:
> ---> 36             return function(self, *args, **kwargs)
>      37 
>      38         else:
> 
> TypeError: sample() got an unexpected keyword argument 'conditions'
> 
> In [7]:                                                                                                                                                                                                            
> ```
> 
> I will create a pull request and upgrade the [BTB](https://github.com/MLBazaar/BTB/) copulas version so it can be installed and used with `SDV`.
> 
> I'm closing this issue since an error is already displayed when you are using the wrong version of copulas with `SDV`:
> 
> ```
> ERROR: sdv 0.8.0 has requirement copulas<0.6,>=0.5.0, but you'll have copulas 0.3.2 which is incompatible.
> ```

However, I tried (both) when using copulas 0.3.2 or 0.5.0 in my environment, all failed... and both have type error... And then I tried with the demo code, also have the same error.
```
import pandas as pd
from sdv.demo import load_tabular_demo
data = load_tabular_demo('student_placements')
model = GaussianCopula()
model.fit(data)
model.sample(200)
```
Also fails...

**Comment by pvk-developer** [comment] 2021-04-06 18:41
> 
> @pvk-developer However, I tried (both) when using copulas 0.3.2 or 0.5.0 in my environment, all failed... and both have type error... And then I tried with the demo code, also have the same error.
> 
> ```
> import pandas as pd
> from sdv.demo import load_tabular_demo
> data = load_tabular_demo('student_placements')
> model = GaussianCopula()
> model.fit(data)
> model.sample(200)
> ```
> 
> Also fails...

If the code is run inside a jupyter-notebook or ipython there is no `autoreload` by default, which usually requires a kernel restart, and there is a chance that when the newer `copulas` version was installed the kernel was still running with the older version. 

I can recommend you to run `pip uninstall baytune` and then `pip install copulas==0.5.0` while you turn off the `jupyter-notebook` or `ipython` and then relaunch your session. If you would like to ensure that all the dependencies are properly installed you can run `pip check`. 

If I run `pip check` on my current install you will see which packages are causing dependency issues:
```
$ pip check
sdv 0.8.0 has requirement copulas<0.6,>=0.5.0, but you have copulas 0.3.2.
pycaret 2.3.0 has requirement scikit-learn==0.23.2, but you have scikit-learn 0.24.0.
```

You can also create a new `virtualenv` and install only `sdv` and try to run our demo again, which should work.
