### ISSUE TITLE
Models incorrectly generating constant data

### ISSUE THREAD

**Issue by gnomesanta** [sdv-dev/SDV#1592] opened 2023-09-19 06:53 UTC
### Environment Details

* SDV version: 1.2.0
* Python version: 3.10.6
* Operating System: Ubuntu 22.04.1

### Error Description

I used the Gaussian Copula synthesizer and CTGAN synthesizer to generate some synthetic data. Both synthesizers incorrectly generate a constant value for one of my columns, which is a numeric variable. I have noticed that the constant value generated is the minimum value of my original column. 

I have checked my metadata to ensure that the column type is correctly input as numeric. I have also investigated the learned beta distributions so I don't think there is any issue there. 

Assistance appreciated, thanks in advance!

**Comment by npatki** [comment] 2023-09-20 13:49
Hi @gnomesanta, nice to meet you. Seems like an unintended edge case of some sort.

We usually start by trying to replicate your issue so we can look into it further. Would you be able to provide us with some more details that would help us with this? I'm thinking the following:

1. What is the min/max values of your real data? And is there any rounding in place (eg. 2 decimal digits)?
2. How is the data being stored? If you have a dataframe, you can use `dataframe.dtypes` to print out the storage types for each column.
3. You mentioned investigating the learned beta distribution. Could you specify the parameters you see? (I believe there should be `a, b, loc, scale`)
4. Your code when you are fitting/sampling the synthesizer. I'm particularly interested in whether you're applying any constraints (`add_constraints`), data preprocessing (`update_transformers`) or conditional sampling?

**Comment by gnomesanta** [comment] 2023-09-21 07:14
hi @npatki nice to meet you too! I have provided some further details below

1. min/max are 18.28 and 46.33 respectively, all the data are 2 dp. 
2. I am reading my csv file using read_csv. The variable in question is float64. 
3. ```{'distribution': 'beta', 'learned_parameters': {'loc': -78.23275036821482, 'scale': 2.3433513325141828e-30, 'a': 2170684.123605152, 'b': 84151.30493077749}}```
4. No additional constraints

Thanks for your help!

**Comment by npatki** [comment] 2023-09-21 14:41
Hi @gnomesanta, thanks for the details. I am able to see the issue.

1. Based on the parameter values in (3), it seems like the beta distribution parameters are not being properly fit to your data column. With a loc of `-78` and a scale very close to `0`, this distribution is only capable of producing values at around `-78.233`
2. By default the SDV enforces min/max values. Since `-78.233` is less than the observed min, the SDV is clipping this value to the observed minimum which is `18.28`
3. Therefore, all observed values in the synthetic data are `18.28`

### Some Next Steps
I would recommend upgrading to the latest SDV version (1.4.0) in case any of the latest changes will help with this issue.

If you are continuing to see this issue, a workaround may be to choose another distribution shape besides `'beta'` for this column. Perhaps a `'truncnorm'` or `'uniform'` just to test with? You can use the `numerical_distributions` parameter to change this. (See [API docs](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer#parameter-reference)).

In the meantime, I'm wondering if you'd be able to **share your data with us**? This will be extremely useful for the SDV team to replicate and provide fixes. I understand that your data may be private. Even sharing just this column could be helpful. Let us konw.

### Technical Notes

- We are using the [scipy's beta distribution](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.beta.html) to perform the fit. Have we found a case where scipy is failing?

**Comment by gnomesanta** [comment] 2023-09-22 05:02
Hi @npatki , thanks for looking into this! 

So first up, I tried upgrading sdv, still getting the same results. 

I will try your suggestion of inputting a different distribution. However, I am using the sdv models on large datasets, and it might not be feasible to check all the columns, and subsequently specifying different distributions for some of them. 

I have attached the particular column here. So with using the Gaussian Copula and CopulaGAN synthesizers, I get a constant value of the minimum of the column. However with CTGAN and TVAE, I am able to synthesize the data in line with expectations. 

Thanks again!

[sdv_issue_1592.csv](https://github.com/sdv-dev/SDV/files/12696931/sdv_issue_1592.csv)

**Comment by npatki** [comment] 2023-09-22 19:36
Really appreciate you sending over the data @gnomesanta. We had heard of the constant data issue from other users, but for the first time we are able to properly replicate it :) 

### Root cause
We use scipy for some of the underlying estimations and I can confirm that scipy is failing to converge on this data. The [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.fit.html#scipy.stats.rv_continuous.fit) do warn that convergence isn't guaranteed.

>  the returned answer is not guaranteed to be globally optimal; it may only be locally optimal, or the optimization may fail altogether

### Factors that contribute to this
You are more likely to hit these edge cases in the following scenarios:

1. There are many missing values. The SDV provides basic pre-processing to handle missing values, but it is not designed to handle sparser datasets. For eg, I noticed that your column has 20% missing values.
    - **We can file a separate feature request to track this for you.**
    - To prioritize, am curious to know the origin of the dataset and what type of project you're working on? 
3. You're using the `'beta'` distribution. You can set the distribution for all columns at once using the `default_distribution` parameter. I recommend trying `truncnorm`.

**Comment by npatki** [comment] 2023-09-27 20:36
Hi @gnomesanta, after discussing with the team we believe biggest cause of this to be amount of missing values in the data (over 20%). Our preprocessing is not designed to handle such a large portion of missing values.

Ultimately, the fix would require a different type of imputation for missing values in the preprocessing stage. We've identified the core fix in the RDT library that we use for pre-processing. See [RDT Issue #606](https://github.com/sdv-dev/RDT/issues/606) for more information.

We can still keep this issue open until we have made the RDT fix and verified that it works in the SDV, end-to-end.

**Comment by gnomesanta** [comment] 2023-10-04 09:41
Hi @npatki , thanks for your input! 

I have tried the truncnorm distribution as the default for the whole dataset, and it works now. But I am curious as to why a different distribution will work? Since you mentioned that the initial issue was due to imputation of missing values, I assume that this imputation process is the same regardless of distribution used. So is the problem due to the distribution or the imputation of missing values?

I can try the models again when the RDT fix is implemented. Any idea on the timeline for this?

Lastly, regarding your queries on my dataset, it is a longitudinal study so there is bound to be missing data. The goal is to generate synthetic data that maintains the relationship between my variables as much as possible, which ideally includes the pattern of missing-ness across variables. 

Any advice appreciated!

**Comment by npatki** [comment] 2023-10-04 21:56
Hi @gnomesanta, we're actively working on the RDT issue and hope to include in the following release if all goes well. Probably a few weeks.

> is the problem due to the distribution or the imputation of missing values?

It is a mix of your particular data (with high % missing value), the imputation strategy, and the distribution shape that is being used. Our imputation fix should make it the edge case less likely for all distribution shapes. (Though do note from my earlier comment that scipy never guarantees an ideal, global optimization for any shape.)

>  which ideally includes the pattern of missing-ness across variables

Thanks for the description. I'm curious -- is the missing-ness of a value meaningful to your application? For example, is it indicative of a particular scenario occurring or trend?

**Comment by npatki** [comment] 2023-11-08 15:21
Hi @gnomesanta, great news. The RDT issue has been resolved and you should be able to fix this issue by updating your preprocessing.

### Step 1: Upgrade Software
To use the latest data pre-processing techniques, you'd need to upgrade the SDV to the latest 1.6.0 (today's release). Test your version using the following:

```python
import sdv
print(sdv.__version__)
```

It should be 1.6.0

### Step 2: Update Preprocessing
Now, you'll have additional pre-processing options. For columns with **high amounts of missing values**, I recommend using a new strategy called `'random'` for imputing those missing values.

```python
from rdt.transformers.numerical import FloatFormatter

# create 1 transformer for each column with highly missing values
var1_imputer = FloatFormatter(missing_value_replacement='random', enforce_min_max_values=True, learn_rounding_scheme=True)

# assign the transformers to those columns
synthesizer.auto_assign_transformers(data)
synthesizer.update_transformers({
    'var1': var1_imputer
})

# now you can fit and sample
synthesizer.fit(data)
synthetic_data = synthesizer.sample(num_rows=500)
```

**Comment by npatki** [comment] 2023-11-08 15:22
I'm closing this issue off since we confirmed the above code now works for the CSV you shared. Please let me know if you're having any problems with it. We can always reopen the issue to discuss.

**Closed by npatki** 2023-11-08 15:22 UTC
Labels: bug
