### ISSUE TITLE
FutureWarning: Future versions of RDT will not support the 'model_missing_values' parameter. Please switch to using the 'missing_value_generation' parameter to select your strategy.

### ISSUE THREAD

**Issue by alextopology** [sdv-dev/SDV#1615] opened 2023-10-02 15:29 UTC
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.3.0
* Python version:3.11.4
* Operating System: windows

### Problem description

<I am using SDV to synthesize OTU table and i would like to use the CTGAN synthesizer, but during the fitting i encounter this warning: FutureWarning: Future versions of RDT will not support the 'model_missing_values' parameter. Please switch to using the 'missing_value_generation' parameter to select your strategy. When i use the FAST ML preset synthesyzer everything works. What can i do to fix this problem?>

### What I already tried

<I searched for SDV documentation, to search for the missing_value_generation parameter but i can t find anything>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment] 2023-10-02 20:05
Hi @alextopology, nice to meet you.

Rest assured that **there is no problem** with how you are using CTGAN, and **there is no issue with the algorithm**. The message is indicating that an (internal) parameter name has slightly changed. But it is only a warning -- nothing to worry about right now! 

### Additional Context
The message is due to how CTGAN is internally is preprocessing the data. The fix has already been merged into the codebase and will be available after we make the next CTGAN release (see related issue SDV #1544, and CTGAN [#310](https://github.com/sdv-dev/CTGAN/pull/310) ). 

Hope that answers your question.

**Comment by alextopology** [comment] 2023-10-02 20:11
Shouldn't have not should have, sorry for the typo.

Il Lun 2 Ott 2023, 22:10 Alessio Rotelli ***@***.***> ha
scritto:

**Comment by alextopology** [comment] 2023-10-02 20:25
But I would like to ask another question if it s not a problem, why when I
start synthesizing data after i restarted the session, the synthesizer
start always with the same data in a specific order?

Il Lun 2 Ott 2023, 22:11 Alessio Rotelli ***@***.***> ha
scritto:

**Comment by npatki** [comment] 2023-10-03 05:30
Hi @alextopology, no problem.

> i have modified that parameter from
the CTGAN/ctgan/data_transformer.py

I would recommend not changing the internals of the SDV libraries, as it may be harder to upgrade the libraries after the new releases. And we would not be able to help you debug if you have injected your own code.

Is there a reason you want to get rid of the warning? It has no effect on the algorithm or its output. You can safely ignore the warning.

> why when I
start synthesizing data after i restarted the session, the synthesizer
start always with the same data in a specific order?

I would suggest for new topics, you can file a new issue. That way we can close each issue when we are done discussing the topic (or fixing the code).

To answer this Q: This is currently done by design, as many users have wanted to generate data in a deterministic way. But you can always continue to sample a synthesizer to get new data every time. See also, the [reset sampling API](https://docs.sdv.dev/sdv/single-table-data/sampling/sample-realistic-data#reset_sampling).

**Comment by alextopology** [comment] 2023-10-03 11:20
So i should restore the original line of code? Model_missing_values = () i
do not remember what there was in the parenthesis.

Il Mar 3 Ott 2023, 07:30 Neha Patki ***@***.***> ha scritto:

**Comment by npatki** [comment] 2023-10-04 21:58
Hi @alextopology, perhaps a fresh install of the SDV would reset it back to its original state? Alternatively, you can look through the codebase here on GitHub, but that would be the harder approach.

**Comment by npatki** [comment] 2023-10-13 18:59
Hi @alextopology, we recently [updated the CTGAN library](https://github.com/sdv-dev/CTGAN/releases/tag/v0.7.5), which addresses the FutureWarning message you were seeing.

To get the latest updates, I'd recommend starting with a clean Python environment where you can do a fresh installation of the SDV library. Just today, we have release [SDV v1.5.0](https://github.com/sdv-dev/SDV/releases/tag/v1.5.0).

**Closed by npatki** 2023-10-13 18:59 UTC
Labels: question, under discussion
