### ISSUE TITLE
Error while using UniqueCombinations on CTGAN

### ISSUE THREAD

**Issue by jrmelog** [sdv-dev/SDV#364] opened 2021-03-26 13:30 UTC
### Environment Details

* SDV version:  0.8.0
* Python version: Python 3.8.2
* Operating System: Windows

### Error Description

I tried to use UniqueCombinations on CTGAN in a dataset called "Estados" that has two categorical columns  "unidade" and "sigla", first I created the constraint as below 

`constraint = UniqueCombinations(columns=['unidade', 'sigla'], handling_strategy='transform')` 

after that I created the CTGAN model `model = CTGAN(constraints=constraints)` and when I tried to fit the model `model.fit(estados)`, it showed the error `Invalid columns found: {'sigla', 'unidade'}
`

Code:

```
estados = pd.read_csv('estados.csv')
UF_constraint = UniqueCombinations(columns=['unidade', 'sigla'], handling_strategy='transform')
constraints = [UF_constraint]
model = CTGAN(constraints=constraints)
model.fit(estados)
```

Traceback:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-08221acb8659> in <module>
----> 1 model.fit(estados)

~\anaconda3\envs\mpdl\lib\site-packages\sdv\tabular\base.py in fit(self, data)
    117             LOGGER.debug(
    118                 'Fitting %s model to table %s', self.__class__.__name__, self._metadata.name)
--> 119             self._fit(transformed)
    120 
    121     def get_metadata(self):

~\anaconda3\envs\mpdl\lib\site-packages\sdv\tabular\ctgan.py in _fit(self, table_data)
     49         ]
     50 
---> 51         self._model.fit(
     52             table_data,
     53             discrete_columns=categoricals

~\anaconda3\envs\mpdl\lib\site-packages\ctgan\synthesizers\ctgan.py in fit(self, train_data, discrete_columns, epochs)
    261                 a ``pandas.DataFrame``, this list should contain the column names.
    262         """
--> 263         self._validate_discrete_columns(train_data, discrete_columns)
    264 
    265         if epochs is None:

~\anaconda3\envs\mpdl\lib\site-packages\ctgan\synthesizers\ctgan.py in _validate_discrete_columns(self, train_data, discrete_columns)
    247 
    248         if invalid_columns:
--> 249             raise ValueError('Invalid columns found: {}'.format(invalid_columns))
    250 
    251     def fit(self, train_data, discrete_columns=tuple(), epochs=None):

ValueError: Invalid columns found: {'sigla', 'unidade'}
```

**Comment by jrmelog** [comment] 2021-03-26 14:28
I tried to use the SDV demo dataset `from sdv.demo import load_tabular_demo` on CTGAN and CopulaGan, but the same error occurs `ValueError: Invalid columns found: {'company', 'department'}` in both models. 

```
unique_company_department_constraint = UniqueCombinations(columns=['company', 'department'],handling_strategy='transform')
constraints = [unique_company_department_constraint]
model = CopulaGAN(constraints=constraints)
model.fit(employees)
```

**Comment by csala** [comment] 2021-03-26 14:36
Thanks for reporting this @jrmelog!

It is surprising that it fails on the demo, because demos are thoroughly tested regularly on the CI pipelines, so there may be something else affecting this.

Would you mind reporting the output of a `pip freeze` command?

I'll see if I can reproduce this on my side too.

**Comment by jrmelog** [comment] 2021-03-26 14:55
The `pip freeze` output:

`argon2-cffi @ file:///C:/ci/argon2-cffi_1596828585465/work
async-generator==1.10
attrs @ file:///tmp/build/80754af9/attrs_1600298409949/work
backcall==0.2.0
bleach @ file:///tmp/build/80754af9/bleach_1600439572647/work
certifi==2020.6.20
cffi @ file:///C:/ci/cffi_1600699246375/work
colorama @ file:///tmp/build/80754af9/colorama_1603211150991/work
copulas==0.4.0
ctgan==0.3.1
cycler==0.10.0
decorator==4.4.2
deepecho==0.1.4
defusedxml==0.6.0
dython==0.5.1
entrypoints==0.3
et-xmlfile==1.0.1
Faker==4.14.2
graphviz==0.16
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1602276842396/work
ipykernel @ file:///C:/ci/ipykernel_1596190155316/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1598865816163/work
ipython-genutils==0.2.0
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1601490159889/work
jdcal==1.4.1
jedi @ file:///C:/ci/jedi_1598353661586/work
Jinja2==2.11.2
joblib @ file:///tmp/build/80754af9/joblib_1601912903842/work
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1601311786391/work
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1598884538475/work
jupyter-core==4.6.3
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
kiwisolver==1.2.0
llvmlite==0.35.0
MarkupSafe==1.1.1
matplotlib==3.1.3
mistune==0.8.4
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
nbclient @ file:///tmp/build/80754af9/nbclient_1602783176460/work
nbconvert @ file:///C:/ci/nbconvert_1601914925608/work
nbformat @ file:///tmp/build/80754af9/nbformat_1602783287752/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1601499549014/work
networkx==2.5
notebook @ file:///C:/ci/notebook_1601501643625/work
numba==0.52.0
numpy==1.18.1
openpyxl==3.0.5
packaging==20.4
pandas==1.1.4
pandocfilters==1.4.2
parso==0.7.0
patsy==0.5.1
pickleshare==0.7.5
Pillow==8.0.1
pomegranate==0.13.4
prometheus-client==0.8.0
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
psutil==5.8.0
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
Pygments @ file:///tmp/build/80754af9/pygments_1600458456400/work
pyparsing==2.4.7
pyrsistent @ file:///C:/ci/pyrsistent_1600141795814/work
python-dateutil==2.8.1
pytz==2020.1
pywin32==227
pywinpty==0.5.7
PyYAML==5.4.1
pyzmq==19.0.2
qtconsole @ file:///tmp/build/80754af9/qtconsole_1600870028330/work
QtPy==1.9.0
rdt==0.3.0
scikit-learn==0.22.1
scipy @ file:///C:/ci/scipy_1592916963468/work
sdmetrics==0.1.3
sdv==0.7.0
seaborn==0.11.1
Send2Trash==1.5.0
sip==4.19.13
six==1.15.0
sktime==0.5.3
statsmodels==0.12.2
table-evaluator==1.2.2.post1
terminado==0.9.1
testpath==0.4.4
text-unidecode==1.3
torch==1.7.1
torchvision==0.5.0
tornado==6.0.4
tqdm==4.57.0
traitlets @ file:///tmp/build/80754af9/traitlets_1602787416690/work
typing-extensions==3.7.4.3
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
widgetsnbextension==3.5.1
wincertstore==0.2
zipp @ file:///tmp/build/80754af9/zipp_1603306325174/work`

**Comment by MLjungg** [comment] 2021-03-29 11:27
I raised this issue a couple of weeks back (https://github.com/sdv-dev/CTGAN/issues/133), after which Fealho solved it in the following pr (https://github.com/sdv-dev/SDV/pull/332). So I'd suggest you update SDV in case you don't have the latest version.

**Comment by jrmelog** [comment] 2021-03-29 12:36
I updated and still got the same error, @MLjungg.

**Comment by fealho** [comment] 2021-03-30 03:58
Hi @jrmelog, as @MLjungg mentioned, #332 fixed this issue, but it hasn't been released it yet. A new version of SDV containing the fix should be released this week though, so if you update it then it should work.

**Comment by fealho** [comment] 2021-04-09 14:55
Closing, since the new release fixed this issue.

**Closed by fealho** 2021-04-09 14:55 UTC
Labels: bug
