### ISSUE TITLE
FastML adding extra decimal places from a monetary column

### ISSUE THREAD

**Issue by seanbenjaDEADBEEF** [sdv-dev/SDV#1796] opened 2024-02-16 20:57 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.0.6
* Python version: 3.11
* Operating System: Windows [10](url)

### Error Description

I have a dataset with a "billing" column where each entry has 1, 2, or 3 digits to the left of the decimal place, and 2 digits to the right of the decimal. However, after running fit the digits to the right of the decimal can be up to 17.  Neha recommended submitting a bug report.

### Steps to reproduce

Metadata billing column is defined as:

metadata.add_column(
    column_name='billing',
    sdtype='numerical') # I tried versions of 'currency' but could get none to work, so i settled on 'numerical'

Then...

# convert column to string
# note down the # of digits after the decimal pt
column_string = real_data['billing'].astype('string')
digits_after_decimal = column_string.apply(lambda x: len(x.split('.')[1]))

# print min and max # of digits
print('Min digits after decimal point', min(digits_after_decimal))
print('Max digits after decimal point', max(digits_after_decimal))

->
Min digits after decimal point 1
Max digits after decimal point 2

Then...

synthesizer.fit(
    data=real_data
)

synthetic_data = synthesizer.sample(
    num_rows=2000
)

# convert column to string
# note down the # of digis after the decimal pt
column_string = synthetic_data['billing'].astype('string')
digits_after_decimal = column_string.apply(lambda x: len(x.split('.')[1]))

# print min and max # of digits
print('Min digits after decimal point', min(digits_after_decimal))
print('Max digits after decimal point', max(digits_after_decimal))

->
Min digits after decimal point 2
Max digits after decimal point 17

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
No errors or crashes.

**Comment by srinify** [comment] 2024-02-20 20:41
Hi there @seanbenjaDEADBEEF I work with Neha on the Datacebo team.

I was able to reproduce the issue you ran into with the Fast ML synthesizer. I swapped out this synthesizer for the GaussianCopula synthesizer instead and all of the synthetically generated values contained only 2 decimal values.

This requires only 2 changes -- a different import statement and swapping out the Synthesizer class you use:

```
from sdv.single_table import GaussianCopulaSynthesizer

# synthesizer = SingleTablePreset(metadata, name='FAST_ML') 
synthesizer = GaussianCopulaSynthesizer(metadata)
synthesizer.fit(df)
```

I would also recommend upgrading to the latest version of sdv if you can (`pip install sdv==1.10.0`)

**Comment by srinify** [comment] 2024-02-20 21:37
Created separate new issue to focus just on this fast ML bug.

Duplicate of https://github.com/sdv-dev/SDV/issues/1796

**Comment by srinify** [comment] 2024-02-20 21:39
Created separate new issue to focus just on this Fast ML Preset Synthesizer bug.

Duplicate of #1806

**Closed** 2024-02-21 15:51 UTC
Labels: bug, under discussion
