### ISSUE TITLE
HMASynthesizer generates IDs in order (even though real data has random IDs)

### ISSUE THREAD

**Issue by majidliaquat** [sdv-dev/SDV#1596] opened 2023-09-20 14:12 UTC
As I am using HMAsynthesizer for Multitables it works fine, but when I generate synthetic data then the generated data are not similar to real data. In below section I tried to explain the issue in detail that I am facing.

## Issue with generated data

As I generted data by adjusting the table parameters mentioned earlier. You can see the refer image below:

![multiTableData](https://github.com/sdv-dev/SDV/assets/13814086/1257eb64-f972-40c5-9363-8b83760d508c)

The Parent Table (Real Data) have shape of `4500, 4` in real dataset the `account_id` has random data, _as one highlighted in row 51_ . 

Again if you have a look at the generated data which also have same shape of `4500, 4` but the problem is that the data I am getting with _account_id data which starts from **0 to 4,499**_ same as index. (Highlighted with red and orange box).

I want the generated data also be random as like the real data. Here are the table parameters I set:

``` 
synthesizer.set_table_parameters(
                       table_name='parent table',
                       table_parameters={
                           "enforce_min_max_values":true
                              "enforce_rounding":true
                              "locales":"en_GB"
                              "numerical_distributions":{
                              "account_id":"norm"
                              }
                              "default_distribution":"uniform"
                       }
                   )
```

I refer the documentation on website [Documentation](https://docs.sdv.dev/sdv/multi-table-data/modeling/synthesizers/hmasynthesizer) but couldn't find something related to this issue.

Thanks in advnce
Many Thanks,
Majid

**Comment by npatki** [comment] 2023-09-20 20:35
Hi @majidliaquat,

Thanks for filing this issue with this example. I'm going to re-title this issue to be more precise about the nature of the problem.

In the SDV, we consider the purpose of ID columns to be unique identifiers (in the case of a primary key), or part of a relationship (in the case of a foreign key). So a lot of our users have not found it necessary to follow any specific patterns in the data. I think we can mark this as a new feature request, since the code itself is working as intended.

To help us prioritize, it would be great to provide a bit more information about your use case. **Why is having random IDs a requirement for your project?** Are you planning to use the synthetic data in a way that requires this randomness?

If I can understand the nature of this concern, then I can try to suggest other workarounds for you too. Thanks.

**Comment by majidliaquat** [comment] 2023-09-25 09:16
Hi @npatki, 

Thank you for your response. In my case as the real table there was some missing values I drop them so now I get random number of IDs. Actually I need random IDs as in some tables those IDs representing a place name in other table. 

So I was just worndering if we can generate random IDs that will be better for the generated table to be more realistic which also improve on quality score.

I was thinking if we pass parameters  with `set_table_parameters` and generate random numbers for specific ID:

```
synthesizer.set_table_parameters(
                       table_name='parent table',
                       table_parameters={
                              "numerical_distributions":{
                              "account_id":"norm",
                               "min_id_value":0,
                              "max_id_value":1000
                              }
                              "default_distribution":"uniform"
                       }
                   )
```
It may be not the way I am passing, because I didn't test it yet.

Thanks

**Comment by npatki** [comment] 2023-09-25 21:09
Hi @majidliaquat, the `numerical_distributions` parameter does not support min or max values.

I think if your IDs are specifically referring to a different concept or table, then it wold be best to mark them as `"categorical"` in the metadata. That way, the SDV will learn correlations between those IDs and other columns. It will then recreate the same IDs in the output. [This blog post](https://datacebo.com/blog/categorical-data/) has more information about when you should consider something categorical.

It would be very helpful if you could provide the metadata file so we could assist you further.

**Comment by majidliaquat** [comment] 2023-09-27 08:56
Hi @npatki, 

Here is the metadata with parent with two child tables:

```
{
  "tables": {
    "Table 1 account.csv": {
      "columns": {
        "account_id": {
          "sdtype": "id"
        },
        "district_id": {
          "sdtype": "id"
        },
        "frequency": {
          "sdtype": "categorical"
        },
        "date": {
          "sdtype": "numerical"
        }
      },
      "primary_key": "account_id"
    },
    "Table 2 loan.csv": {
      "columns": {
        "loan_id": {
          "sdtype": "id"
        },
        "account_id": {
          "sdtype": "id"
        },
        "date": {
          "sdtype": "numerical"
        },
        "amount": {
          "sdtype": "numerical"
        },
        "duration": {
          "sdtype": "numerical"
        },
        "payments": {
          "sdtype": "numerical"
        },
        "status": {
          "sdtype": "categorical"
        }
      },
      "primary_key": "loan_id"
    },
    "Table 3 order.csv": {
      "columns": {
        "order_id": {
          "sdtype": "id"
        },
        "account_id": {
          "sdtype": "id"
        },
        "bank_to": {
          "sdtype": "categorical"
        },
        "account_to": {
          "sdtype": "numerical"
        },
        "amount": {
          "sdtype": "numerical"
        },
        "k_symbol": {
          "sdtype": "categorical"
        }
      },
      "primary_key": "order_id"
    }
  },
  "relationships": [
    {
      "parent_table_name": "Table 1 account.csv",
      "child_table_name": "Table 2 loan.csv",
      "parent_primary_key": "account_id",
      "child_foreign_key": "account_id"
    },
    {
      "parent_table_name": "Table 1 account.csv",
      "child_table_name": "Table 3 order.csv",
      "parent_primary_key": "account_id",
      "child_foreign_key": "account_id"
    }
  ],
  "METADATA_SPEC_VERSION": "MULTI_TABLE_V1"
}
```
I will try what you are suggesting after reading the blog post.

Many Thanks.

**Comment by npatki** [comment] 2023-09-27 20:31
Hi @majidliaquat, thanks for providing the metadata. I have a follow-up question. Earlier you have mentioned:

> Actually I need random IDs as in some tables those IDs representing a place name in other table.

In the example, you are wanting random IDs for the `account_id` variable (in the accounts table). But from the metadata, it seems like `account_id` seems to be listed as a primary key, so I am a bit confused.

Generally, a primary key is a unique identifier to the table that's defined in. So how can it be a primary key and _also_ represent a place name in another table? Could you explain that a bit more.

**Comment by majidliaquat** [comment] 2023-09-29 09:07
Hi @npatki,

Yes the metadata I provided is not about that what I mentioned before. I have two tables in which there is district names and ID and another table just the district ID (as foreign Key). For that reason I asked for the random ID's with in a range.

I am using the dataset: **1999 Czech Financial Dataset - Real Anonymized Transactions** 

here is the datamap:
![image](https://github.com/sdv-dev/SDV/assets/13814086/0c60d8df-91c8-4e41-872a-40197601dc30)

Many Thanks.

**Comment by npatki** [comment] 2023-10-03 05:39
Hi @majidliaquat, I am still a bit confused. Would it be possible to provide the metadata for this schema and the relevant column(s) that are giving you problems? Is `district_id` the primary key of `Demograph`?

When the SDV generates multi-table data, it will guarantee the following:

1. **Primary keys** of a table will always be a unique identifier (it will follow the Regex format you can optionally provide), and
2. **Foreign keys** will always point to primary keys in a different table. That is: The references will be consistent.

So if `district_id` is a foreign key in a table, then the values will be pointing to the primary key of a different table. 

If you have the metadata, that will help me understand what's happening. Thanks.

**Comment by Abduttayyeb** [comment] 2023-11-17 05:20
Hello @npatki !
I wanted to know that the foreign keys can have repeated values as well right ? so for example

CustID | QuoteID | CustDetails 
  001          2344           Lorem
  002          2344           Lorem
  003          2142           Lorem
  
  Here QuoteID -> ForeignKey
  But when SDV gives the output, It changes the custID as well as QuoteID to something like this

  CustID | QuoteID | CustDetails 
     0          0                    Lorem
     1          1                    Lorem
     2          2                    Lorem
     
     
Instead The QuoteID should have repeated values as this is a foreignKey and it is expected to have values based on the relationship with the parent table.

**Comment by npatki** [comment] 2024-04-22 21:28
Closing as a duplicate of #1922 -- we will now scramble up the IDs so that they do not appear in order. This will make the IDs appear more in order.

Note that for some cases (like small batch sampling), this may not appear as random. Truly random ID generation is something the team is actively working on.

**Closed by npatki** 2024-04-22 21:28 UTC
Labels: feature request
