### ISSUE TITLE
Tabular models: Add option to randomize ids

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDV#329] opened 2021-03-02 21:17 UTC
### Problem Description

Current primary key ids are generated sequentially. It would be interesting to have an option to generate them in a random order.

### Expected behavior

The `sample` method of the tabular models should include a `random_ids` (default `False`) that if set to `True` would make the `ids` be generated in random order.

**Comment by npatki** [comment] 2024-04-17 02:44
Closing as a dupe of #1596

**Closed by npatki** 2024-04-17 02:44 UTC
Labels: feature request
