### ISSUE TITLE
Improve HMA1 modeling & sampling time

### ISSUE THREAD

**Issue by erenarkangil** [sdv-dev/SDV#830] opened 2022-06-01 09:29 UTC
Hi there,

What I have tried:

Using HMA model to generate traffic demand data. Libraries are updated.

The trip dataset contains generally origin-destinations as categoric variables, which creates a big load on memory, for example if you have 4000 origin destinations, it creates 4000^2 columns with one hot encoding. I tried switch from one hot encoding to categorical_fuzzy in my code, but still it was not sufficient to solve this complexity. Dimensionality reduction wouldn't work because I want to keep the trip data. Are there any strategy to handle with such big cardinality?

Kind Regards.

**Comment by npatki** [comment] 2022-06-01 22:08
Hi @Erenhub, is the traffic demand dataset a publicly available one? If not, are you able to provide metadata for it?

> I tried switch from one hot encoding to categorical_fuzzy in my code, but still it was not sufficient to solve this complexity.

I'm curious what measures you are using to say it's "not sufficient" (time, memory usage etc.). Usually switching to `categorical fuzzy` encoding solves the problem. If you can paste in the code where you are creating your model, I can see if there is anything being mishandled in the fuzzy computation.

**Comment by npatki** [comment] 2022-06-03 20:20
Thanks for the detailed info @Erenhub. I can confirm that the code looks correct for what you're trying to do.

The SDV team is actively working the performance characteristics. Though this is not your intended usage, I'm curious what the performance is like without the constraint?

Some other things to try:

1. I've had more success using `{'categorical_transformer': 'label_encoding' }` for high dimensionality data. You might want to give this a try.
2. We recently released a `FAST_ML TabulaPreset` that is optimized for speed. Though this is only for a single table, this might give you a useful datapoint re best case speed. [This User Guide](https://sdv.dev/SDV/user_guides/single_table/tabular_preset.html) has more details, including the following benchmarks:
    - Datasets with around 100K rows and 50-100 columns will take a few minutes to model
    - Larger datasets with around 1M rows and hundreds of columns may take closer to an hour

If it's ok with you, I suggest we re-purpose this issue to be about the HMA1 performance characteristics and keep it filed as a feature request.

**Comment by Erenhub** [comment] 2022-06-09 02:16
Hi @npatki , thanks for your guidance. I have been trying to do it with coordinates to reduce complexity. Since it is not categoric, It works perfectly, however, It is far from generating realistic trips between two point. Do you think there could be any constraint to solve this problem?

Without the constraints, the performance did not change much.

Thanks.

<img width="1792" alt="Screen Shot 2022-06-09 at 12 14 34 pm" src="https://user-images.githubusercontent.com/47353633/172749717-cbe58678-6f0c-4c8e-9b13-878b2df75802.png">

**Comment by npatki** [comment] 2024-04-17 03:23
Closing off this older issue. Since the last discussion, the team has made a number of updates with SDV 1.0+

- The [HSASynthesizer](https://docs.sdv.dev/sdv/multi-table-data/modeling/synthesizers/hsasynthesizer) is now the preferred approach for dealing with large datasets or complex schemas. This synthesizer is much faster than HMA for both modeling and sampling. _Note that it requires a paid SDV plan. To learn more, visit our [plans page](https://datacebo.com/pricing/)._
- We have added a GPS column relationship specifically for lat/lon pairs [see API](https://docs.sdv.dev/sdv/reference/metadata-spec/multi-table-metadata-json#column-relationships)

**Closed by npatki** 2024-04-17 03:23 UTC
Labels: feature request, data:multi-table, feature:performance
