### ISSUE TITLE
Incorrectly enforced rounding on numerical/float data columns

### ISSUE THREAD

**Issue by dionman** [sdv-dev/SDV#1039] opened 2022-09-28 15:30 UTC
### Error Description

I’m fitting CT-GAN and TVAE on the attached halfmoon dataset (using the default parameters). When sampling from the model I get the float variables discretised to the closest integer. Have you observed behaviour like this in any other settings? It seems to me it’s probably due to some transformation. (I’m using the `fit_sample()` function as defined in the `SDGym` repo to fit the model and sample from it). On the other hand, I can get sane output if I instead use `fit()` and `sample()` as implemented in `ctgan.synthesizers.ctgan.CTGANSynthesizer()`
[halfmoon.zip](https://github.com/sdv-dev/SDV/files/9666608/halfmoon.zip)

**Comment by npatki** [comment] 2022-09-28 16:31
Hi @dionman thanks so much for filing this and providing the data/metadata. Confirmed that I can replicate.

The issue appears to be in how we're learning & enforcing rounding. Only the wrappers in `sdv` have this feature, so the underlying ML model in `ctgan` library is unaffected.

From some of my own experiments, I've found the following:

1. There is a `learn_rounding_scheme` [parameter](https://sdv.dev/SDV/api_reference/tabular/api/sdv.tabular.ctgan.CTGAN.html#sdv.tabular.ctgan.CTGAN) when creating the model. But turning it to `False` does not help.
2. The rounding is being done by the RDT library right now. There seems to be an issue when the # of digits >14 (see [issue](https://github.com/sdv-dev/RDT/issues/556))

### Workaround

If it doesn't affect quality too much, I'd suggest just rounding your data to the first 14 digits before training the model.

```python
rounded_data = data.round(14)
model.fit(rounded_data)
```

### Fixes
The RDT library should be fixed, we actually plan to stop using RDT for rounding in future SDV releases. We should continue to keep this issue open until we verify a fix.

Separately, I'm not sure why `learn_rounding_scheme` cannot be turned off right now. I'll file another issue to track this.

**Comment by npatki** [comment] 2022-09-29 14:19
Let's keep this one open until we fix & verify the underlying bug all the way throughout the SDV.

**Comment by npatki** [comment] 2023-03-10 01:01
Hi everyone, great news! This issue has now been resolved in the new, [**SDV 1.0 (Beta!)**](https://docs.sdv.dev/sdv) release.

Fore more information and to get started, see the [SDV 1.0 demos](https://docs.sdv.dev/sdv/demos).

**Closed by npatki** 2023-03-10 01:01 UTC
Labels: bug, data:single-table
