### ISSUE TITLE
How to run SDV on single table data with relational columns.

### ISSUE THREAD

**Issue by kvrameshreddy** [sdv-dev/SDV#170] opened 2020-07-21 12:29 UTC
* SDV version:v0.3.5 - 2020-07-09

* Python version:3.7
* Operating System:windows 8.1

### Description

How to generate single table data using SDV With columns having relation like(Company-Department or Country-State)

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by csala** [comment] 2020-07-28 10:55
Hi @kvrameshreddy 

A few days ago we made a new release that introduced Constraints to SDV.

Among other things, we added the `UniqueCombinations` constraint which solves the problem that you are describing (the sampled data should only contain the combinations of certain columns seen during training).

We are still adding documentation to them but you can already have a look at how they work on this notebook: https://github.com/sdv-dev/SDV/blob/master/tutorials/05_Constraints_Usage_Example.ipynb

Please have a look and give it a try or let me know if you have any doubts about how to use them.

**Comment by kvrameshreddy** [comment] 2020-07-28 11:10
@csala Thank you this thing worked for me. But for fitting data and sample generation the model is taking more time. Is there any way to reduce the execution time

**Comment by csala** [comment] 2020-10-13 07:37
Duplicate of #166, which has already been closed.

**Closed by csala** 2020-10-13 07:37 UTC
Labels: duplicate
