### ISSUE TITLE
RuntimeWarning: invalid value encountered in log.

### ISSUE THREAD

**Issue by R-Palazzo** [sdv-dev/SDV#1364] opened 2023-04-06 08:46 UTC
### Problem Description

Running the `sdv/tests` with `pytests` raised the following warning:

`RuntimeWarning: invalid value encountered in log.`

### Expected behavior

We want to modify the code to no longer get this warning.

### Additional context

Here is given the code line in `sdv` that raised the warning. Because this list may be incomplete, it would be nice to check after the correction that the warning is not in the `warning summary` of `pytests`.

#### Line to be modified:

```
/sdv/constraints/tabular.py:484
```

**Comment by npatki** [comment] 2023-04-12 18:44
This looks to be a duplicate of #1275, so I'm closing it off. We can use the older issue to track this.

**Closed by npatki** 2023-04-12 18:44 UTC
Labels: internal
