### ISSUE TITLE
unable to run this code from sdv.demo import load_tabular_demo

### ISSUE THREAD

**Issue by mansiresh** [sdv-dev/SDV#2027] opened 2024-05-24 06:29 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:
* Python version:
* Operating System:

### Error Description

<Replace this text with a description of what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.>

### Steps to reproduce

<Replace this text with a description of the steps that anyone can follow to reproduce the error. If the error happens only on a specific dataset, please consider attaching some example data to the issue so that others can use it to reproduce the error.>

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment] 2024-05-24 13:49
Hi @mansiresh I see you left another issue in #2028 that is a duplicate of this one so I'm closing this one off. We can continue discussion in #2028.

**Closed by npatki** 2024-05-24 13:49 UTC
Labels: bug, new
