### ISSUE TITLE
KeyError when using synthesizer.sample()

### ISSUE THREAD

**Issue by mohammedsabiya** [sdv-dev/SDV#1510] opened 2023-07-19 14:03 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version:  1.1.0
* Python version: 3.9.16
* Operating System: macOS Ventura Version 13.4.1

### Error Description

I am getting an error while running the code for PARSynthesizer model. 
The context column in PARSynthesizer is `befund`. 
`befund` is a categorical data type. Each `ID` has different `befund` but it does not vary within a sequence. 

* Training datatype: sequential time series data
* Single table dataset
* `sequence_index` is datetime

### CODE

`from sdv.sequential import PARSynthesizer`

`# Step 1: Create the synthesizer`

`synthesizer = PARSynthesizer(metadata, context_columns=['befund'], enforce_rounding=True, epochs=400, sample_size=50, segment_size=20, verbose=True)`

`# Step 2: Train the synthesizer`
`synthesizer.fit(training_data)`

`# Step 3: Generate synthetic data`
`synthetic_data = synthesizer.sample(100)`
`synthetic_data`

### ERROR MESSAGE

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[15], line 2
      1 # Step 3: Generate synthetic data
----> 2 synthetic_data = synthesizer.sample(100)
      3 synthetic_data

File /Users/hameedharshan/opt/anaconda3/envs/cate_env/lib/python3.9/site-packages/sdv/sequential/par.py:352, in PARSynthesizer.sample(self, num_sequences, sequence_length)
    349     if column not in context_columns:
    350         context_columns[column] = range(len(context_columns))
--> 352 return self._sample(context_columns, sequence_length)

File /Users/hameedharshan/opt/anaconda3/envs/cate_env/lib/python3.9/site-packages/sdv/sequential/par.py:321, in PARSynthesizer._sample(self, context_columns, sequence_length)
    320 def _sample(self, context_columns, sequence_length=None):
--> 321     sampled = self._sample_from_par(context_columns, sequence_length)
    322     return self._data_processor.reverse_transform(sampled)

File /Users/hameedharshan/opt/anaconda3/envs/cate_env/lib/python3.9/site-packages/sdv/sequential/par.py:297, in PARSynthesizer._sample_from_par(self, context, sequence_length)
    295 for sequence_key_values, context_values in iterator:
    296     context_values = context_values.tolist()
--> 297     sequence = self._model.sample_sequence(context_values, sequence_length)
    298     if self._sequence_index:
    299         sequence_index_idx = self._data_columns.index(self._sequence_index)

File /Users/hameedharshan/opt/anaconda3/envs/cate_env/lib/python3.9/site-packages/deepecho/models/par.py:549, in PARModel.sample_sequence(self, context, sequence_length)
    546     max_length = self._max_length
    548 if self._ctx_dims:
--> 549     context = self._context_to_tensor(context).unsqueeze(0)
    550 else:
    551     context = None

File /Users/hameedharshan/opt/anaconda3/envs/cate_env/lib/python3.9/site-packages/deepecho/models/par.py:268, in PARModel._context_to_tensor(self, context)
    266     if pd.isnull(value):
    267         value = None
--> 268     x[props['indices'][value]] = 1.0
    270 else:
    271     raise ValueError()

KeyError: 'N000'

```

The 'N000` in KeyError: 'N000'` is one of the categories of `befund`

**Comment by npatki** [comment] 2023-07-21 04:11
Hi @mohammedsabiya, thanks for filing the issue and including all the details.

Unfortunately, I'm not able to replicate it based on the description alone. I wonder if there is any other information you'd be able to provide to help us replicate it? The following might be helpful:

1. Can you share your `metadata.json` file? It would be helpful to know the data types of all the columns (the names are not as important)
2. In your data, how many sequences are there? You can count the # of unique sequence keys to find this out
3. In your data, how long are the sequences? If they vary, providing the min/max lengths would be useful. You can use the code below.

```python
# replace 'sequence_key' with the name of your sequence key
lengths = training_data.groupby(['sequence_key']).count().reset_index()['befund']

print('Min sequence length:', min(lengths), 'rows')
print('Max sequence length:', max(lengths), 'rows')
```

**Comment by npatki** [comment] 2023-07-25 04:41
Hi @mohammedsabiya thanks for the info. Unfortunately, I'm still unable to replicate the error that you're seeing. (It's working fine if I try to sample with similar data.)

Here are a few more things we can try:

1. Could you also provide the `dtype` of each column in your input data? I'm wondering if there's any unexpected mismatches between the reported sdtype and how it's actually stored in your DataFrame. You can get these using the following:
```python
print(training_data.dtypes)
```
2. Can you confirm that this issue remains if you change the epochs? (For example, whether setting `epochs=1` makes it go away) And whether this Error is consistent? (Whether subsequent calls to `sample` make it go away)
3. For debugging purposes, it may be helpful to print out the following info that is more directly related to the error message
```python
print(synthesizer._model._ctx_map)
```

And of course, if you've been doing your own investigations and have any theories as to the cause, please let us know. This seems like a tough one!

**Comment by mohammedsabiya** [comment] 2023-07-25 08:24
Hi @npatki thank you again!

1. the `dtype` of each column seems okay. Here is the `dtype` of `training_data`:

```
id                               object
date                          object
result                        object
ict                             object
functional_test        object
                ...   
capacitor_third       float64
resistor_first           float64
resistor_second     float64
transistor_first       float64

```

The code works for 1 sample, like the code below:
`synthesizer.sample(1)`

For one sample I get 20 rows of data with the same `sequence key` ID. But if I want to get even two samples, then it throws the same error. Of course, I need more samples. 

2. I facing the same issue as in `1` when I use `epochs=1`

3. when I do `print(synthesizer._model._ctx_map)`, the result I get is:

```
{0: {'type': 'categorical', 'indices': {'B000': 1}}}
```

**Comment by npatki** [comment] 2023-07-27 07:27
Hi @mohammedsabiya some of the `dtype` information is cut off. Can you confirm if they are all either `object` or `float64`?

> when I do print(synthesizer._model._ctx_map), the result I get is: 
{0: {'type': 'categorical', 'indices': {'B000': 1}}}

Just to sanity check, `'B000'` should be one of the categories in the `befund` column. Although it's strange that it is the only one. When I run a PARSynthesizer, I see `_ctx_map` has values for all the possible categories in the context column. For example, if I have categories `'A', 'B', 'C'`, then I see:

```
{ 0: 
    {
        'type': 'categorical',
        'indices': {
            'A': 1,
            'B': 2,
            'C': 3
         }
    }
}
```

So this does validate that something is going wrong, but I'm still not entirely sure why. Is there anything different about the sequence with context `'B000'`?

Other than that, it would be really helpful if you are able to share some data that would help us replicate, as we still haven't been able to get this error to trigger. Any subset or anonymized version of the data would be helpful. (And if you're more comfortable sharing this privately, we can also set that up!)

**Comment by mohammedsabiya** [comment] 2023-07-31 07:27
@npatki if you would like to have the dataset as a file, please let me know

**Comment by mohammedsabiya** [comment] 2023-08-02 07:35
@npatki  Hi, I am facing the same problem again even with Google Colab. I just realised that I was training the `PARSynthesizer` model without `befund` as `context_columns`, that's why I did not have any problem while sampling more samples.  

Now, when I add `befund` as `context_columns`,  the same error occurs.

I have attached a pdf that lists the installed libraries.

[installed_libraries.pdf](https://github.com/sdv-dev/SDV/files/12237308/installed_libraries.pdf)

**Comment by npatki** [comment] 2023-08-03 16:42
@mohammedsabiya ahh bummer! In that case, would you mind sharing the CSV for the input data that is triggering this issue? I'd love to be able to replicate this at least once. Thanks!

**Comment by npatki** [comment] 2023-09-20 20:09
Hi @mohammedsabiya, were you ever able to get to the bottom of this issue? I'm closing it as one of the ones we unfortunately were unable to replicate (for a few months now). But if you ever want to continue this investigation, please feel free to reply and we can re-open the issue.

For what it's worth, I think you have a lot of different libraries installed in your environment. It's possible there are some interactions with bad versions of different libraries. If you are still interested in getting PAR to work, I'd recommend creating a fresh, clean Python environment and _only_ installing the SDV. It would be another thing to rule out.

**Closed by npatki** 2023-09-20 20:09 UTC
Labels: bug, under discussion
