### ISSUE TITLE
Select the categorical transformer based on data properties

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/SDV#581] opened 2021-09-09 04:21 UTC
### Problem Description

Most of the categorical transformers work very well in some scenarios but badly in others. For example, the `one_hot_encoding` transformer seems to work well for categorical variables with low cardinality, while `categorical` and `categorical_fuzzy` work well for higher cardinalities. Other aspects, such as the number of categorical variables in the dataset or how balanced the categorical values are within each column may also play a role.
 
### Expected behavior

We can add an option to optimize the models by selecting the categorical transformer to use based on the properties of the input data.

**Comment by npatki** [comment] 2021-09-21 00:25
Is this optimization for time or quality or both?

If we optimize categorical transformers automatically, it would be nice to provide the results back to the user in some form. Especially if there's a time/quality tradeoff, I might like to know which transforms are used for which columns, plus my options for overriding this.

**Comment by npatki** [comment] 2024-01-08 22:35
Closing as a dupe of #341

**Closed by npatki** 2024-01-08 22:35 UTC
Labels: feature request
