### ISSUE TITLE
HMA1 sdv sample fail using   constraint Inequality comparing datetime64[ns] columns 

### ISSUE THREAD

**Issue by mounirHai** [sdv-dev/SDV#1191] opened 2023-01-26 10:53 UTC
[error.log](https://github.com/sdv-dev/SDV/files/10508458/error.log)
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.17.2
* Python version: 3.7.12
* Operating System: windows 10

### Error Description

when using constraint Inequality with HMA1 model, I get this error when sampling new synthetic data.

### Steps to reproduce

use Inequality constraint with two columns of type datetime64[ns]
metadata description

    "fields": {
         "patientNr": {"ref": {"field": "patientNr", "table": "patient"},
                          "type": "id",
         "subtype": "integer"},
         "referalID": {"type": "id", "subtype": "integer"},
        "referalInnDate" :  {"type": "datetime", "format": "%Y-%m-%d"},
        "referalOutDate" :  {"type": "datetime", "format": "%Y-%m-%d"}   
    },  
    "constraints": [{"constraint": "sdv.constraints.tabular.Inequality",
    "low_column_name": "referalInnDate","high_column_name":"referalOutDate"}],        
    "primary_key": "referalID"
    }
```
my_model_kwargs ={'default_distribution': 'gaussian','categorical_transformer':'LabelEncoder_noised'}
model = HMA1(metadata=metadata,model_kwargs=my_model_kwargs)
model.fit(real_data),
model.sample()
```

**Comment by npatki** [comment] 2023-01-30 16:05
Hi @mounirHai, thanks for filing the request. I can replicate this and we have an ongoing issue #1213 to fix this in future versions of the SDV. (Note that that we are slightly changing the API so the code snippets in that issue are slightly different from today's methods.)

### Workaround 
In the meantime, there is a workaround you can use to emulate the logic of the `Inequality` constraint. It does require some manual work:

**Before modeling**:
1. Create a new column `referalDiff` that is computes: `referalOutDate - referalInnDate ` (converted to a float or integer)
2. Drop the `referalOutDate` column
3. Put this new data into the model.

**After modeling**: Recover the original columns
1. Recreate `referalOutDate` using the formula `referalInnDate + referalDiff`
2. Now you can drop the `referalDiff` column you created.

**Comment by mounirHai** [comment] 2023-01-31 09:57
Thanks for the reply! I applied the workround before I finally opted for the constraint Inequality. The reason is that I was not happy with the model performance and the total score using the diff column. One more  thing ! teh  sampling with num_ rows=1500 goes fine withput any  Overflow error. sampling 2000 and above and the error shows up again.

**Comment by npatki** [comment] 2023-01-31 15:25
Hi @mounirHai,

> The reason is that I was not happy with the model performance and the total score using the diff column

Would you be able to describe this more? I'm curious what performance characteristics you are measuring. And I wonder which "total score" you are looking at?

> sampling with num_ rows=1500 goes fine withput any Overflow error. sampling 2000 and above and the error shows up again.

Would you be able to [file a new issue](https://github.com/sdv-dev/SDV/issues/new/choose) for this? Any other details -- such as the code you tried, the full error message and stack trace would be helpful.

**Comment by mounirHai** [comment] 2023-02-01 13:46
Hi npatki 
for the sampling issue, I filled a new issue with log files https://github.com/sdv-dev/SDV/issues/1221

regarding the performance of the HMA1 model (my_model_kwargs ={'default_distribution': 'gaussian','categorical_transformer':'LabelEncoder_noised'} )with constraints on date and Versus the date diff variable, here are the overall quality scores:


- with Inequality constraint on date variables sample 2000
Overall Quality Score: 81.02%

Properties:
Column Shapes: 83.89%
Column Pair Trends: 67.87%
Parent Child Relationships: 91.31%


- with diff date
Overall Quality Score: 74.43%

Properties:
Column Shapes: 79.53%
Column Pair Trends: 59.11%
Parent Child Relationships: 84.64%

quite a diffrence!

**Comment by npatki** [comment] 2023-02-01 17:24
@mounirHai thanks!

Very interesting results. The actual `Inequality` constraint does a little bit more math behind-the-scenes rather than doing a simple subtraction. I wonder if this is why it's much better.

**Full Logic**:
1. Take the difference between high and low column
2. Create a log column : `log(difference + 1)`
3. Drop the high column

Thus, it models the only the low column and the log column
Upon sampling synthetic data, you can then reverse the logic:

1. Actual difference: `e^(log_column) - 1`
2. Create high column: `low_column + difference`

Now you can drop the `log_column`

Could you try that to see if it works?

**Comment by mounirHai** [comment] 2023-02-02 16:12
Hi npatki.
you were right the performance with diff on the dates columns come closer to the performance of the model with Inequality constraint on date (I did not use the log transform to make the diff column more gaussian in teh previous post)

with Inequality constraint on date (sample 2000)
Overall Quality Score: 81.02%

Properties:
Column Shapes: 83.89%
Column Pair Trends: 67.87%
Parent Child Relationships: 91.31%


with diff date
Overall Quality Score: 81.57%

Properties:
Column Shapes: 85.18%
Column Pair Trends: 69.22%
Parent Child Relationships: 90.3%

**Comment by npatki** [comment] 2023-02-02 17:42
Hi @mounirHai,

I assumed from your earlier comment that a simple diff was not good enough, as it gave you a quality score of 74.43%? Maybe I misunderstood.

In any case, I'm glad you were able to get better results! I suggest we close this issue as a duplicate of #1213, for fixing the root cause in `HMA` going forward.

_If there's anything more to discuss, feel free to reply here and I can reopen to investigate. Alternatively, you can also add thoughts to #1213._

**Closed by npatki** 2023-02-02 17:42 UTC
Labels: bug, feature:constraints, data:multi-table, under discussion
