### ISSUE TITLE
PARSynthesizer: dates duplicates in synthetic data

### ISSUE THREAD

**Issue by louisedry-quinten** [sdv-dev/SDV#1723] opened 2023-12-19 16:35 UTC
I am trying to synthesize ICU data from the MIMIC-III dataset. I have several continuous time-sensitive features (such as the BPM for example) retrieved every hour for 24 hours, so I have 24 buckets for each patient. 
These values are retrieved at **regular time intervals** and I would like the synthetic data to showcase it but it doesn't. Instead, I have sequences that can be days, months or even years appart from each other when it should be 1 hour. I think this case is mentioned in #829. Any update on this ? 

Also, I have noticed that some sequences can appear on the same sequence index. For example, when running the tutorial available on sdv (https://colab.research.google.com/drive/1YLk2uwn8yrSRPy0soEeJwu8Hdk_tGTlE?usp=sharing#scrollTo=YYVfVBOnJ5Jd), I have noticed that in my synthesized data there were duplicates in the date column for one Symbol type (see picture).
![image](https://github.com/sdv-dev/SDV/assets/149507610/ec61c00e-d6e4-4d2b-a2c2-d322d5408b69)

As you can see I have higlighted in red two sequences happening on the same day and in yellow two other sequences happening on another same day. This doesn't seem very logical.
In my case I wish to synthesize health data so I can't have a patient with several vital values at one point in time. Is there any way to avoid this ?

**Comment by npatki** [comment] 2024-01-03 01:22
Hi @louisedry-quinten thanks for pointing this out. I think what you are observing can be broken down into two problems:

1. The `time_index` column contains duplicate values within the same sequence. It is expected to increment in every row of the same sequence so it should never be duplicate. Let's use this issue to track and provide updates for this problem.
2. If the `time_index` values increment by some regular interval (eg. every day), then the synthetic data is expected to have the same patterns. This is covered by #829. Any progress or updates that we make will show up in the issue. Unfortunately, the team has been busy with other features but as we see more people encountering the problem, it definitely helps us prioritize.

**Comment by Ng-ms** [comment] 2024-01-23 22:40
Hello @louisedry-quinten  were you able to overcome the time index problem by using the PAR or any other method ?

**Comment by louisedry-quinten** [comment] 2024-01-24 08:28
> Hello @louisedry-quinten were you able to overcome the time index problem by using the PAR or any other method ?

Hello @Ng-ms unfortunately no I could not find a solution.

**Comment by npatki** [comment] 2024-01-25 14:52
Hi @Ng-ms and @louisedry-quinten, 

Unfortunately, the date duplication problem appears to be a quality issue, and I can't think of a quick fix or guaranteed workaround for it. You an always try updating the number of epochs to see if a longer training session would. Ultimately, the solution will require some more involved changes in the PAR algorithm. We can keep this issue open to track it, as well as communicate any updates or insights.

**Comment by npatki** [comment] 2024-01-26 20:41
Update on this: We have identified a root cause, which is now linked in #1760. You can follow that issue for an update.

Please note that this may not be the _only_ root cause so until we resolve #1760, we will keep this one open.

**Comment by npatki** [comment] 2024-02-20 21:12
Hi @Ng-ms and @louisedry-quinten,

Good news -- this issue should be fixed in the latest SDV release (1.10.0). Please upgrade for the latest result.

On the NASDAQ demo dataset, I've confirmed that there are no duplicate values within a single stock's sequence.

![image](https://github.com/sdv-dev/SDV/assets/3227804/7ec9af0d-d5be-42ac-bfc5-71a3a0dcbc12)

Do note that _if_ your real data contains duplicate values, then your synthetic data would as well -- as the synthesizer learns what is possible based on your real data. Please feel fee to reach out if you have any questions. Thanks.

**Closed by npatki** 2024-02-20 21:12 UTC
Labels: feature request, under discussion
