### ISSUE TITLE
TypeError: Cannot interpret 'CategoricalDtype(categories=['[1] Male', '[2] Female'], ordered=False, categories_dtype=object)' as a data type

### ISSUE THREAD

**Issue by ltptnt** [sdv-dev/SDV#1733] opened 2024-01-06 10:53 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.8.0
* Python version: 3.11.5
* Operating System: Windows 11

### Error Description
I was attempting to generate synthetic data using a trained synthesizer. The `synthesizer.fit(data)` function threw a TypeError when it reached the first categorical column in the dataframe.

### Steps to reproduce
1. Find a dataset with categorical data
2. Run the following code

```
from sdv.single_table import CTGANSynthesizer
from sdv.metadata import SingleTableMetadata
from sdv.evaluation.single_table import run_diagnostic, evaluate_quality
import pandas as pd
import pyreadstat
import os

DATA_PATH = "data/"
OUTPUT_PATH = "output/"
FILE_EXTENSION = ".sav"

data = pd.read_spss("data.sav")

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data)

synthesizer = CTGANSynthesizer(metadata)
synthesizer.fit(data)

synthetic_data = synthesizer.sample(data.shape[0])
```

Traceback:
```
Traceback (most recent call last):
  File "folder\convert.py", line 64, in <module>
    convert(file)
  File "folder\convert.py", line 40, in convert
    synthesizer.fit(data)
  File "folder\.venv\Lib\site-packages\sdv\single_table\base.py", line 437, in fit
    self.fit_processed_data(processed_data)
  File "folder\.venv\Lib\site-packages\sdv\single_table\base.py", line 420, in fit_processed_data
    self._fit(processed_data)
  File "folder\.venv\Lib\site-packages\sdv\single_table\ctgan.py", line 313, in _fit
    self._model.fit(processed_data, discrete_columns=discrete_columns)
  File "folder\.venv\Lib\site-packages\ctgan\synthesizers\base.py", line 50, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "folder\.venv\Lib\site-packages\ctgan\synthesizers\tvae.py", line 155, in fit
    self.transformer.fit(train_data, discrete_columns)
  File "folder\.venv\Lib\site-packages\ctgan\data_transformer.py", line 106, in fit
    column_transform_info = self._fit_discrete(raw_data[[column_name]])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "folder\.venv\Lib\site-packages\ctgan\data_transformer.py", line 75, in _fit_discrete
    ohe.fit(data, column_name)
  File "folder\.venv\Lib\site-packages\rdt\transformers\base.py", line 55, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "folder\.venv\Lib\site-packages\rdt\transformers\base.py", line 390, in fit
    self._fit(columns_data)
  File "folder\.venv\Lib\site-packages\rdt\transformers\categorical.py", line 594, in _fit
    if not np.issubdtype(data.dtype, np.number):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "folder\.venv\Lib\site-packages\numpy\core\numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
TypeError: Cannot interpret 'CategoricalDtype(categories=['[1] Male', '[2] Female'], ordered=False, categories_dtype=object)' as a data type
```

`pip list` output:
```
Package           Version
----------------- ------------
boto3             1.34.14
botocore          1.34.14
cloudpickle       2.2.1
colorama          0.4.6
contourpy         1.2.0
copulas           0.9.2
ctgan             0.8.0
cycler            0.12.1
deepecho          0.5.0
Faker             19.13.0
filelock          3.13.1
fonttools         4.47.0
fsspec            2023.12.2
graphviz          0.20.1
Jinja2            3.1.2
jmespath          1.0.1
joblib            1.3.2
kiwisolver        1.4.5
MarkupSafe        2.1.3
matplotlib        3.8.2
mpmath            1.3.0
networkx          3.2.1
numpy             1.26.3
packaging         23.2
pandas            2.1.4
pillow            10.2.0
pip               23.3.2
plotly            5.18.0
pyparsing         3.1.1
pyreadstat        1.2.6
python-dateutil   2.8.2
pytz              2023.3.post1
rdt               1.9.0
s3transfer        0.10.0
scikit-learn      1.3.2
scipy             1.11.4
sdmetrics         0.13.0
sdv               1.8.0
setuptools        65.5.0
six               1.16.0
sympy             1.12
tenacity          8.2.3
threadpoolctl     3.2.0
torch             2.1.2
tqdm              4.66.1
typing_extensions 4.9.0
tzdata            2023.4
urllib3           2.0.7
```

**Comment by npatki** [comment] 2024-01-08 23:07
Hi @ltptnt, nice to meet you. Thanks for including all the details. Fixing this issue requires a bit of understanding about the data types.

### Background
The SDV uses metadata as the ground source-of-truth. SDV uses a special version of data types known as `sdtypes` ([See API](https://docs.sdv.dev/sdv/reference/metadata-spec/sdtypes)).

The metadata auto-detection is able to guess the stypes, but is they are not guaranteed to be correct. I would recommend you carefully inspect the metadata and update any incorrect columns -- mark discrete columns as "categorical", continuous values as "numerical", etc. Then save the data. For more info, see the [Metadata API](https://docs.sdv.dev/sdv/single-table-data/data-preparation/single-table-metadata-api). 

The sdtype is completely separate from the storage type -- eg. int64, float64, etc. The error you are getting indicates that the _storage type is incompatible with SDV_. 

### The Fix
You can print the data storage type using the following command:

```python
print(data.dtypes)
```

SDV has been tested extensively with  `int64`, `float64` and `object`. So if you notice _anything_ else popping up here (eg. such as `category`) then we recommend casting it to a compatible storage type. Eg.

```python
# cast a column named 'gender' to be stored as an 'object'
data['gender'] = data['gender'].astype('object')
``` 

Then fitting and sampling should work as intended. _Remember that as long as the metadata has the correct sdtypes, SDV will model the columns correctly, regardless of how they are stored._
 
### Next Steps
- I have filed a new issue at #1735 to provide more user-friendly error when you hit this case 
- Root cause: [RDT #751](https://github.com/sdv-dev/RDT/issues/751)

**Comment by npatki** [comment] 2024-01-29 21:14
Hello, did this workaround help?

I'm going to close off this issue as a duplicate of the issue #1763, which is a feature request we created explicitly for supporting the dtype `'category'`. If you have any further questions, please feel free to reply to #1763 directly. Thanks.

**Closed by npatki** 2024-01-29 21:14 UTC
Labels: bug, under discussion
