### ISSUE TITLE
Unique Constraint doesn't work

### ISSUE THREAD

**Issue by montasIET** [sdv-dev/SDV#1298] opened 2023-03-06 15:53 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.17.2
* Python version: 3.8
* Operating System: W11 Pro

### Error Description

As discussion title says, the unique constraint doesn't work. I inserted the constraint in metadata like this (at the same level of the keyword 'fields':
```
 "constraints": [
                {
                    "constraint": "sdv.constraints.tabular.Unique",
                    "column_names": ["MY_COLUMN"]
                }
]
```

**Comment by npatki** [comment] 2023-03-07 17:14
Hi @montasIET thanks for filing.

To help us replicate this, would you be able to describe what is happening when say that it doesn't work? For eg, the synthesizer is crashing, the synthetic data is not as expected, etc.

Also, it will be helpful to share the full metadata as well as the code that you are using to do the modeling and sampling.

**Comment by montasIET** [comment] 2023-03-10 08:28
Hi @npatki, nothing in particular, this is the strange thing. The HMA1 works without errors but the column is not Unique as it is supposed to be

**Comment by npatki** [comment] 2023-03-10 15:58
Hi @montasIET, I didn't realize you're using the multi-table HMA1. There is a known issue #1102 where the `Unique` constraint doesn't work for multi-table due to our sampling logic. (Note that all other constraints work just fine!)

Let's defer to this issue for future conversation! I've just left a potential workaround that you may be able to use.

**Comment by npatki** [comment] 2023-03-10 15:58
Closing this issue off as a duplicate, as you can reply to #1102 with more details. But if you believe this is caused by something different, please feel free to reply and we can reopen!

**Closed by npatki** 2023-03-10 15:58 UTC
Labels: bug, feature:constraints, under discussion
