### ISSUE TITLE
Saving a fitted tabular model with UniqueCombinations constraint raises PicklingError: Can't pickle <class 'pandas.core.frame.Pandas'>

### ISSUE THREAD

**Issue by prithvidc** [sdv-dev/SDV#286] opened 2020-12-27 01:36 UTC
* SDV version:sdv-0.6.0
* Python version:python3.6
* Operating System:Google Colab (linux1_x86_64)

### Description

Describe what you were trying to get done.
I am using CTGAN model with UniqueCombinations constraint with handling_strategy='transform', trained for single-table data. When I try to save the model to .PKL fail, I get failure response. I was able to generate sample data using model.sample(), but could not save.

### What I Did

- I removed all rows with NaN values in the source data

- Since the training time for a CTGAN synthetic data generation model takes a long time, I sampled only 200 rows from the source data.
 
- The source data contains 3 columns that should be a unique combination: ("Suburb", "CouncilArea", "Regionname"). This is similar to ("City", "Country")
 
- I setup the constraint as follows:
unique_Regionname_CouncilArea_Suburb_constraint = UniqueCombinations(
columns=['Regionname', 'CouncilArea', 'Suburb'],
handling_strategy='transform'
)

- I have 1 constraint:
- constraints = [
unique_Regionname_CouncilArea_Suburb_constraint,
]

- I setup the CTGAN model as below:
from sdv.tabular import CTGAN

model = CTGAN(
anonymize_fields={'address': 'Address'},
constraints=constraints
)

- I trained the model as below:
model.fit(sample_real_data_frame_dataset)
 
- I generated the synthetic data generation as below:
sample_synthetic_data_frame_dataset = model.sample(10)

- I tried to save the model to .PKL file 
model.save('melbourne-housing-snapshot_gen_data_model.pkl')
PicklingError                             Traceback (most recent call last)
<ipython-input-54-8b6d3c54dc67> in <module>()
----> 1 model.save('/content/drive/My Drive/Study/30DaysOfPython/data/melbourne-housing-snapshot/melbourne-housing-snapshot_gen_data_model.pkl')

/usr/local/lib/python3.6/dist-packages/sdv/tabular/base.py in save(self, path)
    226         """
    227         with open(path, 'wb') as output:
--> 228             pickle.dump(self, output)
    229 
    230     @classmethod

**PicklingError: Can't pickle <class 'pandas.core.frame.Pandas'>: attribute lookup Pandas on pandas.core.frame failed** 

Paste the command(s) you ran and the output.
- I tried to save the model to .PKL file 
model.save('melbourne-housing-snapshot_gen_data_model.pkl')
PicklingError                             Traceback (most recent call last)
<ipython-input-54-8b6d3c54dc67> in <module>()
----> 1 model.save('/content/drive/My Drive/Study/30DaysOfPython/data/melbourne-housing-snapshot/melbourne-housing-snapshot_gen_data_model.pkl')

/usr/local/lib/python3.6/dist-packages/sdv/tabular/base.py in save(self, path)
    226         """
    227         with open(path, 'wb') as output:
--> 228             pickle.dump(self, output)
    229 
    230     @classmethod

PicklingError: Can't pickle <class 'pandas.core.frame.Pandas'>: attribute lookup Pandas on pandas.core.frame failed

**Comment by prithvidc** [comment] 2020-12-27 01:47
I'm changing this bug to INVALID in the summary because "Saving a CTGAN model with UniqueCombinations constraint handling_strategy='transform', causes the column values to NaN. So this is invalid. This ticket is indirectly related to https://github.com/sdv-dev/SDV/issues/285

**Comment by prithvidc** [comment] 2020-12-27 08:27
I was able to use CTGAN model with UniqueCombinations constraint handling_strategy='transform' by training with a large dataset and can generate column values with some non-NaN values. But still cannot save the model.

**Comment by csala** [comment] 2020-12-27 17:32
Thanks again for all the details @prithvidc !

Here's a short snippet reproducing the error using the demo data too:

```python
In [1]: from sdv.demo import load_tabular_demo

In [2]: employees = load_tabular_demo()

In [3]: from sdv.constraints import UniqueCombinations

In [4]: unique_company_department_constraint = UniqueCombinations(
   ...:     columns=['company', 'department'],
   ...:     handling_strategy='transform'
   ...: )

In [5]: from sdv.tabular import GaussianCopula

In [6]: gc = GaussianCopula(constraints=[unique_company_department_constraint])

In [7]: gc.fit(employees)

In [8]: gc.save('test.pkl')
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-8-5cdb72976b7c> in <module>
----> 1 gc.save('test.pkl')

~/Projects/MIT/SDV/sdv/tabular/base.py in save(self, path)
    226         """
    227         with open(path, 'wb') as output:
--> 228             pickle.dump(self, output)
    229 
    230     @classmethod

PicklingError: Can't pickle <class 'pandas.core.frame.Pandas'>: attribute lookup Pandas on pandas.core.frame failed
```

**Comment by csala** [comment] 2020-12-27 17:39
I can confirm that this also happens using `GaussianCopula` (as shown in the example above) and with `reject_sampling` strategy too. On the other side, only `UniqueCombinations` constraint seems to be affected.

I'm changing a bit the title to be more precise.

**Comment by csala** [comment] 2020-12-27 17:59
The problem here seems to be related to the `itertuples` output that is stored in `self._combinations` inside `UniqueCombinations` constraint.

Changing this logic to a `drop_duplicates` together with a `left merge` with indicator and then returning `indicator == 'both'` should fix the problem.

**Comment by csala** [comment] 2020-12-27 18:13
@prithvidc as a workaround, while this is fixed on the code, you can save and load your model using [cloudpickle](https://github.com/cloudpipe/cloudpickle).

The process would be as follows:

1. Install `cloudpickle` using `pip`:

```bash
pip install cloudpickle
```

2. Save the model using cloudpickle:

```python
import cloudpickle

with open('<output-path>', 'wb') as f:
    cloudpickle.dump(model, f)
```

3. Load the model using cloudpickle (if this is done in a different environment, you will also need to install `cloudplickle`):

```python
with open('<output-path>', 'rb') as f:
    loaded_model = cloudpickle.load(f)
```

**Closed** 2020-12-31 14:41 UTC
Labels: bug
