### ISSUE TITLE
KeyError: 'Column_Name'

### ISSUE THREAD

**Issue by H1ndAlmarzooqi** [sdv-dev/SDV#1711] opened 2023-12-08 05:06 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: _1.8.0_
* Python version: _Python 3.10_
* Operating System: _Jupyter Notebook_

### Error Description

_Getting an error when trying to fit the data using the synthesizer. 

KeyError                                  Traceback (most recent call last)
Input In [18], in <cell line: 1>()
----> 1 synthesizer.fit(data_df_1)

File /opt/conda/envs/Python-3.10-Premium/lib/python3.10/site-packages/sdv/single_table/base.py:436, in BaseSynthesizer.fit(self, data)
    434 self._data_processor.reset_sampling()
    435 self._random_state_set = False
--> 436 processed_data = self._preprocess(data)
    437 self.fit_processed_data(processed_data)

File /opt/conda/envs/Python-3.10-Premium/lib/python3.10/site-packages/sdv/single_table/ctgan.py:192, in CTGANSynthesizer._preprocess(self, data)
    190 self.validate(data)
    191 self._data_processor.fit(data)
--> 192 self._print_warning(data)
    194 return self._data_processor.transform(data)

File /opt/conda/envs/Python-3.10-Premium/lib/python3.10/site-packages/sdv/single_table/ctgan.py:167, in CTGANSynthesizer._print_warning(self, data)
    165 def _print_warning(self, data):
    166     """Print a warning if the number of columns generated is over 1000."""
--> 167     dict_generated_columns = self._estimate_num_columns(data)
    168     if sum(dict_generated_columns.values()) > 1000:
    169         header = {'Original Column Name  ': 'Est # of Columns (CTGAN)'}

File /opt/conda/envs/Python-3.10-Premium/lib/python3.10/site-packages/sdv/single_table/ctgan.py:157, in CTGANSynthesizer._estimate_num_columns(self, data)
    154     num_generated_columns[column] = 11
    156 elif sdtypes[column] in {'categorical', 'boolean'}:
--> 157     if transformers[column] is None:
    158         num_categories = data[column].fillna(np.nan).nunique(dropna=False)
    159         num_generated_columns[column] = num_categories

KeyError: 'STUDENT_DEGREE_CODE'_

### Steps to reproduce

pip install sdv

pip install sdmetrics
import sdmetrics
import sdv
print(sdv.__version__)
import pandas as pd

import itc_utils.flight_service as itcfs

readClient = itcfs.get_flight_client()

# NOTE:
#  A limit of 5000 rows has been applied to the request to enable sample previewing.
#  Edit or comment-out row_limit to change or disable the row limit.
#
DWH_Dev_data_request = {
    'connection_name': """xxxx""",
    'interaction_properties': {
        'schema_name': 'xxxx',
        'table_name': 'xxxx'
    }
}

flightInfo = itcfs.get_flight_info(readClient, nb_data_request=DWH_Dev_data_request)

data_df_1 = itcfs.read_pandas_and_concat(readClient, flightInfo, timeout=240)
data_df_1.head(10)

data_df_1.keys()

data_df_1.dtypes

from sdv.metadata import SingleTableMetadata
metadata1 = SingleTableMetadata()

metadata1.detect_from_dataframe(data=data_df_1)

python_dict = metadata1.to_dict()

metadata1.visualize(
    show_table_details='full',
    output_filepath='my_metadata.png'
)

metadata1.validate()

from sdv.single_table import CTGANSynthesizer

synthesizer = CTGANSynthesizer(
    metadata1, # required
    enforce_rounding=False,
    enforce_min_max_values=True,
    epochs=500,
    verbose=True
)

my_constraint = {
    'constraint_class': 'FixedCombinations',
    'constraint_parameters': {
        'column_names': ['STUDENT_DEGREE_CODE', 'ENROLL_STUDENT_DEGREE','CIP_FAMILYNAME']
    }
}

synthesizer.add_constraints(constraints=[
    my_constraint
])

synthesizer.fit(data_df_1)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment] 2023-12-08 15:48
Hi @H1ndAlmarzooqi, thanks for filing this issue.

Could you please **provide the metadata file** so that we can try to replicate this issue? You can save it as a JSON file by doing:
```
metadata1.save_to_json('metadata.json')
```

(We recommend this as best practice anyways)

**Comment by npatki** [comment] 2023-12-12 19:05
Hi @H1ndAlmarzooqi, we have been able to replicate this issue with one of our demo datasets. See #1717 for more information.

I'm closing this issue off as a duplicate of #1717, which we'll keep open and use for tracking/progress updates.

**Closed by npatki** 2023-12-12 19:05 UTC
Labels: bug, feature:constraints, under discussion
