### ISSUE TITLE
Applying multiple `UniqueCombinations` constraints that reference the same column results in error

### ISSUE THREAD

**Issue by tjhallum** [sdv-dev/SDV#577] opened 2021-08-31 14:31 UTC
### Environment Details

SDV version: 0.11.0
Python version: 3.6.8
Operating System: Windows 10

### Error Description

Applying multiple `UniqueCombinations` constraints that reference the same column when fitting TVAE/CTGAN models results in `KeyError: "['error_producing_column_name'] not in index"`.

@npatki / @kveerama: This is the final issue that I mentioned/owed you from our Zoom call a couple of weeks ago.

### Steps to reproduce

This graphic shows the source of the error:
![source_of_error](https://user-images.githubusercontent.com/53157308/131549678-39c01c71-17f4-41bb-8228-2c871b397e63.jpg)

This is a data set of airline flights. Both of the constraints depicted in the above graphic are requisite in order to generate synthetic flights that are realistic. The TVAE/CTGAN models will fit using either of the individual constraints without the other; however, the synthetic flights generated are easily identified as unrealistic.

The full Jupyter Notebook that reproduces this behavior is attached (the notebook pulls it's own data from the web): [generate_adversarial_data-ctgan.zip](https://github.com/sdv-dev/SDV/files/7084669/generate_adversarial_data-ctgan.zip)

**Comment by katxiao** [comment] 2021-09-17 21:17
Hi @tjhallum, thanks for raising this issue! We believe this is a consequence of how we implement the 'transform' handling strategy, and will look into the root cause. We'll have to figure out how to reconcile two UniqueCombinations that reference a shared column.

In the meantime, I'm wondering if using one UniqueCombination that contains all three columns would be a sufficient workaround. More explicitly, instead of defining two separate UniqueCombinations 
```
constraint_0 = UniqueCombinations(columns=['a', 'b'])
constraint_1 = UniqueCombinations(columns=['b', 'c'])
```
we could instead use
```
constraint = UniqueCombinations(columns=['a', 'b', 'c'])
```
This is a more restrictive constraint, but it likely would still achieve the goal of realistic flight data.

**Comment by npatki** [comment] 2021-09-20 19:19
BTW if you upgrade to SDV v0.12.0, the SDV will automatically check for any conflicting constraints and proactively throw out a more helpful error message:

```
Exception: Multiple constraints will modify the same column(s): "{'origin'}",
which may lead to the constraint being unenforceable.
Please use "reject_sampling" as the "handling_strategy" instead.
```

While we discuss this issue further, I'm wondering if you have any thoughts on the fix Katharine mentioned: A `UniqueCombinations` on all 3 columns is a stricter constraint, but still accurate to the data. Will this matter for your use case?

**Comment by katxiao** [comment] 2021-09-21 19:44
@tjhallum I'm going to close this issue for now. Please feel free to re-open it if you have any further questions!

**Comment by tjhallum** [comment] 2021-09-21 21:12
@npatki & @katxiao, apologies! I was planning to reply to this earlier today and I just did not get around to it.

I would like to see this issue re-opened.

From my view, the proposed fix is not acceptable. In the image below, I've color coded the relationship dependencies within the data. In order to get realistic flights using the proposed fix, you'd actually have to have a constraint like:

`constraint = UniqueCombinations(columns=['crs_dep_time', 'crs_arr_time', 'carrier', 'flight_num', 'actual_elapsed_time', 'origin', 'dest', 'dist'])`

And...at that point...the output will be more akin to random copies of the original flights than the goal of actual synthetic flights. If I just wanted random copies of the original flights, there'd be much easier ways to do that than CTGAN/TVAE.

From my view, it really is quite critical that SDV engineer a way for a single column to participate in multiple UniqueCombinations constraints.

Airline Data Dictionary w/ Color Coded Relationships:
![image](https://user-images.githubusercontent.com/53157308/134248393-68d33a0f-f68f-4e32-add4-ec861df1324e.png)

**Comment by katxiao** [comment] 2021-09-22 20:46
Hi @tjhallum, thanks for the update - I'll reopen this issue. I can see how using a UniqueCombination constraint with all the relevant columns would be too restrictive in this scenario. 

We will take a closer look at the airline dataset, and will update this thread when we have a better solution.

**Comment by tjhallum** [comment] 2021-09-22 20:55
@katxiao, sounds good! Thank you 🙏!

**Comment by npatki** [comment] 2022-08-08 22:34
Hi @tjhallum, the latest release SDV v0.16.0 is now able to handle multiple constraints that reference the same columns. Check it out and let us know if you run into any issues.

**Closed by npatki** 2022-08-08 22:34 UTC
Labels: bug, feature:constraints
