### ISSUE TITLE
HMA produces `ValueError` when supplying the `truncnorm` distribution

### ISSUE THREAD

**Issue by majidliaquat** [sdv-dev/SDV#1574] opened 2023-09-11 10:13 UTC
Hi there,

### Why I am here?
I am facing an error while setting Table parameters with HMASynthesizer. I can set the parameters and get the parameters this is working.

### Problem
The Issue I am facing while generating Synthetic Data. I tried many ways but didn't find any solution for this error.

#### Code Part and Method.
I am using in for loop which take all the table names and selected column which I want to add.
The code example for parent table:

 ```
synthesizer.set_table_parameters(
                        table_name='parent table',
                        table_parameters={
                            'enforce_min_max_values': True,
                            'default_distribution': 'truncnorm',
                            'numerical_distributions': { 
                                    'p_table_id': 'uniform' }
                        }
                    )
```
## Error when tried to generate synthetic Data
And I am facing error:

`ValueError: Cannot convert non-finite values (NA or inf) to integer`

### Actions I performed to resolve issue
I check my Tables there is no Nan or Null values with the specific column. I also tried to change the column dType with int64 and float but didn't work for me.

## Any help is appreciated. :) 

Many Thanks,
Majid

**Comment by npatki** [comment] 2023-09-15 14:50
Hi @majidliaquat thanks for filing this issue. The problem may have to do with the type of data that you have in your dataset, rather than null values. I'm curious **if you remove the `set_table_parameters` functionality** then do you still get this error? Knowing this will help us identify the root cause.

BTW we'll be able to help you a lot faster if you're able to provide more information about the issue. To start with, the following will be helpful:
- What is the metadata file you're using?
- What is the **full stack trace** of the error that is getting printed out? Usually, there are several lines of code printed out before the final error message.
- Can you provide the code where you are setting up the synthesizer? In addition to `set_table_parameters`, are there any other features you are using such as constraints?

Thanks!

**Comment by majidliaquat** [comment] 2023-09-20 09:18
Hi @npatki ,

The problem I am facing its with default table parameter ` default_distribution': 'truncnorm'`, I changed it to ` 'default_distribution': 'norm'` or `'default_distribution': 'uniform'` its working and genrating data.

Below the parameters I am using
``` 
synthesizer.set_table_parameters(
                       table_name='parent table',
                       table_parameters={
                           "enforce_min_max_values":true
                              "enforce_rounding":true
                              "locales":"en_GB"
                              "numerical_distributions":{
                              "account_id":"norm"
                              }
                              "default_distribution":"uniform"
                       }
                   )
```
## Issue with generated data

As I generted data by adjusting the table parameters mentioned earlier. You can see the refer image below:

![multiTableData](https://github.com/sdv-dev/SDV/assets/13814086/1257eb64-f972-40c5-9363-8b83760d508c)

The Parent Table (Real Data) have shape of `4500, 4` in real dataset the `account_id` has random data, _as one highlighted in row 51_ . 

Again if you have a look at the generated data which also have same shape of `4500, 4` but the problem is that the data I am getting with account_id are staring from  0 to 4,499 same as index. (Highlighted with red and orange box).

I want the generated data also be random as like the real data.

I hope I explained what I am facing if still its not clear please let me know.

Many Thanks,
Majid

**Comment by npatki** [comment] 2023-09-20 13:44
Hi @majidliaquat,

It seems like you are describing 2 different issues.

1. There is a crash and a `ValueError` if you try to use the `truncnorm` distribution. This goes away when using `'norm'` or `'uniform'`
2. The generated IDs are not random

Is that correct? If so, I would recommend focusing this issue on the first topic only. Please file a separate issue for the second topic.

This will make it easier to reference the issues in the future and mark them as closed when a particular topic has been resolved. Thanks!

**Comment by npatki** [comment] 2023-09-20 20:59
Hi @majidliaquat, getting back to the original question of the `ValueError`: I am still unable to replicate the issue you are seeing. On the demo dataset, the `'truncnorm'` is working fine for me without issues.

If you are able to provide more information, it would help us get to the root cause faster.

> What is the metadata file you're using?
> What is the **full stack trace** of the error that is getting printed out? Usually, there are several lines of code printed out before the final error message.

The stack trace is particularly useful, as it allows us to see which methods the code was on when it crashed.

**Comment by npatki** [comment] 2023-10-03 05:42
Hi @majidliaquat are you still having trouble with the `'truncnorm'` distribution? We recently discovered some issue in the `numerical_distributions` parameter for the **HMA Synthesizer**. Seems like this problem might be related, so I am marking it as a duplicate of #1605.

If you believe it's a different problem, feel free to reply here and we can reopen the issue to investigate. As I mentioned in the previous comment, a **stack trace** would be helpful to help us see what is causing the error.

**Closed by npatki** 2023-10-03 05:42 UTC
Labels: bug, data:multi-table, under discussion
