### ISSUE TITLE
Stops with generating incomplete samples and no error shows

### ISSUE THREAD

**Issue by wzker11** [sdv-dev/SDV#1591] opened 2023-09-19 01:57 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.3.0
* Python version: 3.11.3
* Operating System: Windows

### Error Description

When I generating the synthetic samples by using synthetic_data_custom_constraint = synthesizer.sample(10000), it stops with generating only 32 samples and no error shows.

### Steps to reproduce

Metadata:
user_id : categorical
start : datetime
end : datetime
location_significance : categorical
latitude : numerical
longitude : numerical
address_country : categorical
address_city : categorical
address_city_type : categorical
address_streetname : categorical
location_place_name : categorical
location_place_type : categorical
duration : numerical
weekdays : numerical
hour_of_day_gmt_7 : numerical
latlon : numerical

```
def is_valid_time(column_names, data):
  # start time should be earlier than end time
  start = column_names[0]
  end = column_names[1]
  true_values = (data[start] < data[end]) & (((data[end] - data[start]).dt.total_seconds() / 3600) <= 72 )

  return true_values

def is_valid_latlon(column_names, data):
  # lat and lon should be in Jakarta range
  lat = column_names[0]
  lon = column_names[1]
  latlon = column_names[2]

  # rewards members don't pay an amenities fee
  # everyone else may or may not pay one
  true_values = (round((data[lat]+data[lon]),2) == round((data[latlon]),2))

  return true_values

from sdv.constraints import create_custom_constraint_class

startsmallerthanend = create_custom_constraint_class(
    is_valid_fn=is_valid_time
)
latlonrange = create_custom_constraint_class(
    is_valid_fn=is_valid_latlon
)
synthesizer.add_custom_constraint_class(
    class_object=startsmallerthanend, # name of our class
    class_name='startsmallerthanend'  # the name we'll use to refer to it
)
synthesizer.add_custom_constraint_class(
    class_object=latlonrange, # name of our class
    class_name='latlonrange'  # the name we'll use to refer to it
)
startsmallerthanend = {
    'constraint_class': 'startsmallerthanend',
    'constraint_parameters': {
        'column_names': ['start','end']
    }
}
latlonrange = {
    'constraint_class': 'latlonrange',
    'constraint_parameters': {
        'column_names': ['latitude','longitude','latlon']
    }
}
synthesizer.add_constraints([
    startsmallerthanend,
    latlonrange
])

synthesizer.fit(df)
 synthetic_data_custom_constraint = synthesizer.sample(10000)
```
![266895323-e503fd48-b6f3-44b2-99d8-6674d01c278f](https://github.com/sdv-dev/SDV/assets/80029198/745ef149-2a0e-4a1f-85b2-0f69311d36ad)

**Comment by wzker11** [comment] 2023-09-19 01:58
It solved when I add the parameters batch_size=1000000,max_tries_per_batch = 100000. But may I know what batch_size and max_tires_per_batch should I set to get the whole output? Or I need to try different values each time?
Looking forward to hearing from you! Thank you!

**Comment by npatki** [comment] 2023-09-20 16:11
Hi @wzker11, thanks for providing the detailed code.

Custom constraints require careful attention and may end up being tricky to define, which is generally why we prefer using pre-defined constraints when possible.

In your case, I notice that you have only included `is_valid`. There is no `transform` or `reverse_transform` function. Because of this, the SDV will use a **reject sampling** strategy: it will model and create synthetic data as usual, and throw out invalid rows at the end. That's why you're needing to expand the batch parameters. It may be relatively rare for a sampled row to pass both filters that you've provided.

### Solution

1. For the `startsmallerthanend` constraint, I wonder whether the pre-defined [Inequality](https://docs.sdv.dev/sdv/reference/constraint-logic/predefined-constraint-classes/inequality) constraint will work for you. If not, I'm curious which functionality it's missing?
2. For the `latlonrange`, it seems like `latlon` column is just a sum of the first two columns. Since this column can be completely, formulaically created from the others, I wonder why it's necessary to include in the SDV for ML modeling? I'd suggest **dropping this column entirely** from your SDV code. You can always recreate it afterwards using a formula (as a final post-processing step).

**Comment by wzker11** [comment] 2023-09-21 04:47
Hi @npatki, thank you for your reply!
For the transform and reverse_transform function, may I know what are these two functions used for? And how should I use that?

1. For the startsmallerthanend constraint, I wonder whether the pre-defined [Inequality](https://docs.sdv.dev/sdv/reference/constraint-logic/predefined-constraint-classes/inequality) constraint will work for you. If not, I'm curious which functionality it's missing?
Yes, Inequality works for me. Thank you!

2. For the latlonrange, it seems like latlon column is just a sum of the first two columns. Since this column can be completely, formulaically created from the others, I wonder why it's necessary to include in the SDV for ML modeling? I'd suggest dropping this column entirely from your SDV code. You can always recreate it afterwards using a formula (as a final post-processing step).
This is the extra column I generated to try to increase the correlation between latitude and longitude. This is because when I show the synthetic data in geospatial way, the points did not fit our original dataset distribution. After I add the latlon column, the result is better. This is the way I'm think to increase the correlation between synthetic lat and lon. Do you have any other method to increase the correlation?

Looking forward to hearing from you! Thank you!

**Comment by npatki** [comment] 2023-09-22 21:33
Hi @wzker11, I'd recommend going through the [custom logic documentation](https://docs.sdv.dev/sdv/reference/constraint-logic/custom-logic) to learn more about the transform/reverse transform functionality. We also provide an example implementation [here](https://docs.sdv.dev/sdv/reference/constraint-logic/custom-logic/example-iftruethenzero).

> This is the extra column I generated to try to increase the correlation between latitude and longitude. 

Thanks for explaining. I understand the theory of this but in practice, this isn't something we recommend because you end up needing constraints -- which may actually undo the logic you added in the first place. (For example the "constraint" I'd recommend would be to drop the latlon column and then re-add it.)

I think the robust solution here is for official support of lat/long pairs with techniques such as [contextual anonymization/extraction](https://datacebo.com/blog/anonymization-techniques/). Would you file a new feature request for this for tracking?

It would also be helpful to know how you are evaluating the synthetic lat/lon data. Are you mapping it? I'm curious to know what all you'd consider invalid (eg. are all locations in the same country? on land? clustered? etc.)

**Comment by npatki** [comment] 2023-10-03 05:48
Hi @wzker11, I filed a new feature request for the explicit support of lat/lon pairs (GPS). We can use it to track a solution. I can mark this issue as a duplicate of the new feature request.

If you are still working on this project and have more to discuss, feel free to respond and I can reopen the issue.

**Closed by npatki** 2023-10-03 05:48 UTC
Labels: bug, under discussion
