### ISSUE TITLE
PARSynthesizer does not capture the numerical values 

### ISSUE THREAD

**Issue by Ng-ms** [sdv-dev/SDV#1823] opened 2024-02-27 21:22 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.9.0
* Python version:3.8.1
* Operating System: Linux

I am using PARsythnizer to generate sequence data; with the numerical columns, the range of the synthetic data is very limited and repetitive for all the sequences; for the real data, the ranges are much wider. For example,
![Screenshot from 2024-02-27 22-15-44](https://github.com/sdv-dev/SDV/assets/17408097/24de950e-a93e-46fc-b510-a991417194dc)
 the range of the first column is from 30 to 235 but in the synthetic data is just from 80 to 90, i am not sure what to change to make the synthesizer have the same range as the real data

**Comment by srinify** [comment] 2024-04-12 16:12
Hi @Ng-ms apologize for the delay here.

Do you mind sharing:

- Your metadata (you can just run `print(metadata)` if your SingleTableMetadata object is named `metadata`). Feel free to rename columns if you want to hide sensitive info
- A few rows of your data that feel representative

This will help us debug what's going on here!

**Comment by srinify** [comment] 2024-04-24 17:44
Closing this issue for now @Ng-ms but please feel free to re-open if you're still running into it!

**Comment by srinify** [comment] 2024-04-30 13:37
Hi there @Ng-ms out of curiosity, what did you set the `epochs` parameter to when you instantiated the PARSynthesizer object? Or did you not set it and use the default value?

**Comment by Ng-ms** [comment] 2024-04-30 19:16
I set the epos to 100, 200, 400, and with all of them ii got the same results, there is always a peak in the middle , I will send the metadata privately on slack

**Comment by srinify** [comment] 2024-05-02 20:56
Hi @Ng-ms after exploring a bit more here, I'd encourage you to try transforming your original data a bit more if increasing the number of epochs isn't working for you:

- You can inspect the RDT transformers SDV is using to prep your data for model fitting: https://docs.sdv.dev/sdv/single-table-data/modeling/customizations/preprocessing
- You can customize the RDT transformations being applied to your data to help more explicitly re-map your data and make it more friendly for modelling

PARSynthesizer is a neural network based model, so besides data preparation and playing with epochs there's unfortunately not much else we can do right now on our end. Over time, we want to find more ways to improve the sequential modeling experience or explore new model architectures entirely but as it stands PARSynthesizer is 'working as intended'.

With all that context in mind, I'm closing out this issue. If you run into more issues with PARSynthesizer, feel free to still open issues and we can investigate those.

**Closed by srinify** 2024-05-02 20:56 UTC
Labels: bug, under discussion
