### ISSUE TITLE
SDV can not learn a sin wave with PAR, is there something wrong?

### ISSUE THREAD

**Issue by silvaac** [sdv-dev/SDV#369] opened 2021-03-29 17:03 UTC
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.8.0
* Python version: 3.8.8
* Operating System: windows 10 Pro (version 20H2)
* numpy:1.20.1
* torch: 1.8.1
* pandas:1.1.4

### Problem description

I am not able to recover the sin wave using PAR. I get random numbers... Configuration looks easy.

### What I already tried

I have tried time series with different length. I first thought that the issue could be not enough data.

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

sequence_index = 'Date'
from sdv.timeseries import PAR
model = PAR(
    sequence_index=sequence_index,
)

x = np.linspace(0,10000,5000)
y = np.sin(2*np.pi*0.0001*x)
z = np.array([x,y]).transpose()
df = pd.DataFrame(z,columns=['Date','logP'])

model.fit(df)

sSin = model.sample(num_sequences=1)

plt.plot(x,y)
plt.plot(sSin.Date,sSin.logP)
plt.show()

```

**Comment by csala** [comment] 2021-03-30 07:53
Thanks for reporting this @silvaac we'll use your code to reproduce it and dig into it.

One doubt I have is: have you tried increasing the epochs number? The default 128 are good for very quick trials, but in general a much larger value is required, up to thousands.

**Comment by silvaac** [comment] 2021-03-30 12:33
Indeed I did not try that! That could be it. Sorry I am quite new. How do you increase the epochs? In fact I did not find docs about how to set different settings. Can you point me to it ?

**Comment by fealho** [comment] 2021-04-09 16:42
Hi @silvaac, I'll be closing this issue since it seems your original question has been answered. 

Regarding your other question, you can check all the available hyperparameters [here](https://sdv.dev/SDV/api_reference/timeseries/api/sdv.timeseries.deepecho.PAR.html#sdv.timeseries.deepecho.PAR). Specifically, I believe `sample_size` and `segment_size` are the two most relevant parameters to your data.

**Closed by fealho** 2021-04-09 16:42 UTC
Labels: pending review, question
