### ISSUE TITLE
GaussianCopula synthesizer not performing well for Conditional Sampling

### ISSUE THREAD

**Issue by javialias** [sdv-dev/SDV#1435] opened 2023-05-18 17:59 UTC
### Environment Details

* SDV version: 1.0.0
* Python version: 3.9.7
* Operating System: Windows

### Error Description

I'm trying to use the `GaussianCopula` synthesizer for imputing missing values. As far as I know, the Conditional Sampling in `GaussianCopula` is implemented by calculating the conditional distribution of the known variables (or at least I understood that when I read the SDV paper), unlike `CTGAN` or `CopulaGAN` that use the reject sampling technique. With this idea, I'm trying to impute missing values of a dataset using the GaussianCopula, training the synthesizer with the rows that have no missings and then sampling with conditions for the rest of them. The problem is that it fails to fill the missing values, since for about half of the rows returns "ValueError: Unable to sample any rows for the given conditions." I would like to get some insights about why this happens and if it could be solved. Also, since the reject sampling technique is not used in GaussianCopula, what does the `max_tries_per_batch ` do?

### Steps to reproduce

First, I divide the dataframe in non-missing/missing rows. Then I do the following:

```
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data=df_non_missing)
synthesizer = GaussianCopulaSynthesizer(metadata)
synthesizer.fit(df_non_missing)
conditions = []
imputed_df = pd.DataFrame(columns=df_missing.columns)
for idx, row in df_missing.iterrows():
    conditions.append(Condition(num_rows=1, column_values = {col: row[col] for col in df_missing.columns if not pd.isnull(row[col])}))
imputed_df= synthesizer.sample_from_conditions(conditions = conditions, max_tries_per_batch = 1000)
```
I also tried with the `sample_remaining_columns` tool by passing each row at a time but still I couldn't get anything.

**Comment by npatki** [comment] 2023-05-19 01:15
Hi @javialias thanks for providing your code snippet and some explanations!

> Also, since the reject sampling technique is not used in GaussianCopula, what does the max_tries_per_batch  do?

In some cases*, the GaussianCopula Synthesizer may not be able to compute the conditional distribution and have to fall back to reject sampling. We've included the parameter in case this happens.

*This may include cases where there are many, overlapping constraints or if there are a computational limitations with inverting the matrix.

> The problem is that it fails to fill the missing values, since for about half of the rows returns "ValueError: Unable to sample any rows for the given conditions."

One problem might be that you are requesting values that the synthesizer believes to be out-of-bounds. By default, [the synthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer#parameter-reference) learns and enforces min/max values. I wonder if your errors will be solved if you turn this feature off.

```python
synthesizer = GaussianCopulaSynthesizer(
    metadata,
    enforce_min_max_values=False
)
```
You would then need to re-fit the synthesizer.

**Comment by javialias** [comment] 2023-05-19 07:07
Hi @npatki! Thank you for your response. I also thought that setting `enforce_min_max_values=False` could solve the problem, but I tried and it kept failing. I'll continue trying changing some parameters to see if it works. If someone is using this synthesizer for similar purposes, please let us know if you succeed.

**Comment by npatki** [comment] 2023-05-19 17:44
@javialias my pleasure. Are you at least able to generate _some_ rows using conditional sampling, or do all the rows fail?

If only some of the rows are failing, then it would be useful to know what they have in common. You can iterate through the conditions one at a time, and inspect which ones are failing.

```python
import pandas as pd

for idx, row in df_missing.iterrows():
    column_values = { col: row[col] for col in df_missing.columns if not pd.isnull(row[col]) }
    condition = Condition(num_rows=1, column_values=column_values)
    try:
        synthesizer.sample_from_conditions(conditions=[condition], max_tries_per_batch=1000)
    except Exception as e:
        print(column_values)
```

BTW we recently update the SDV documentation for conditional sampling and added a [troubleshooting section](https://docs.sdv.dev/sdv/single-table-data/sampling/conditional-sampling#troubleshooting), in case that's helpful

**Comment by javialias** [comment] 2023-05-22 09:24
@npatki yes, I am able to generate some rows for my table. Depending on the conditions, between 30% and 60% of the imputations are achieved. Is it possible to access the covariance matrix of the copula to see why in the rest of the cases it's not possible to invert it? Thanks!

**Comment by npatki** [comment] 2023-05-22 16:58
Hi @javialias I would recommend starting by investigating the question above: Of the rows that are failing, do they have any characteristics in common?

**Comment by npatki** [comment] 2023-06-08 15:27
Hi @javialias, are you still looking into this? It's been a few weeks since the last response so I'm closing this off.

From the discussion so far, I haven't seen any evidence that there are bugs in the synthesizer, just that some conditions may be a bit harder to generate.

If you're able to identify what the rows have in common, then I can try to replicate it and we can continue the investigation. Feel free to reply and I can always reopen the issue.

**Comment by javialias** [comment] 2023-07-25 10:32
Hi @npatki, sorry for taking so long to reply. I'm taking up this project again. I haven't been able to identify any relationship between non-imputed rows. Is there any method that you could suggest me to help me find them? Thanks!

**Comment by npatki** [comment] 2023-07-25 18:59
Hi @javialias no problem. I will reopen the issue.

Since we last replied, the team has found an issue with conditional sampling which may be the root cause: See #1512. This issue specifically happens when there are missing values in your data, which seems to be the case here? Unfortunately, there is no easy workaround to it -- we'll have to make some changes internally.

> Is there any method that you could suggest me to help me find them?

Nothing specifically. If you're able to filter out the rows into 2 groups: (a) one that needs imputation and (b) one that doesn't, then maybe even visually inspecting (a) vs. (b), something would pop up.

**Comment by javialias** [comment] 2023-07-27 09:39
I'm not entirely sure that this is the cause of my problem. In my case, I divide the dataset in the rows that have missing values and the ones that don't have missings. Then I train the GaussianCopula synthesizer only with the rows without missing values. Then I use the (non missing) values of the rows with missing values as conditions for the synthesizer and sample with those conditions, expecting the missings to get completed. In the end, no missing values are entering as training data for the `.fit` or as conditions for the `.sample_from_conditions`. Is it normal to get the error here then?

**Comment by tlranda** [comment] 2023-07-31 16:11
@javialias Given that only certain rows fail, might you be working with conditional sampling on integer data?
SDV re-introduced a bug that causes that to semi-randomly fail based on floating point numerical instability.
See #806 for a MWE and temporary workaround.

I believe the exact line number for the workaround may have changed since my last indicated commit. Given your example near the top of this issue, it could be a similar bug in another portion of the codebase.

**Comment by npatki** [comment] 2023-09-15 15:26
Hi @javialias, I just wanted to check in to see if you're still investigating this problem?

Based on @tlranda 's suggestion above, converting any integer values to floats (during training and conditional sampling) would prevent any numerical instability problems if that's what's causing the problem.

**Comment by npatki** [comment] 2023-09-27 20:28
Hi everyone, it's been a few months and we're still unable to replicate this one exactly. Assuming it's a numerical instability problem, we can defer to #806 for tracking the fix.

As always, happy to reopen the issue if there is anything else that can help us to replicate or confirm the solution for there. You are also welcome to file new issues if you've discovered any other problems.

**Closed by npatki** 2023-09-27 20:28 UTC
Labels: bug, under discussion, feature:sampling
