### ISSUE TITLE
TabularPreset + custom constraint yields `module 'sdv.constraints.tabular' has no attribute 'CustomConstraint'`

### ISSUE THREAD

**Issue by srowen** [sdv-dev/SDV#1188] opened 2023-01-25 15:08 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.18.0
* Python version: 3.9.5
* Operating System: Ubuntu 20.04

### Error Description

Using `TabularPreset` with a custom constraint yields `module 'sdv.constraints.tabular' has no attribute 'CustomConstraint'`. Indeed this class is defined inside a function, and is not a class directly in that module.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File <command-791251337300678>:40
     30 FixedIncrementsWithExclusion = create_custom_constraint(
     31     is_valid_fn=is_valid,
     32     transform_fn=transform,  # optional
     33     reverse_transform_fn=reverse_transform,  # optional
     34 )
     36 salary_divis_500 = FixedIncrementsWithExclusion(
     37     column_names=["salary"], increment=500, exclusion_column="contractor"
     38 )
---> 40 model = TabularPreset(constraints=[salary_divis_500], name='FAST_ML', metadata=metadata)
     41 model.fit(data)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-bcde8fc9-f418-415d-b8c1-379e0fea2b65/lib/python3.9/site-packages/sdv/lite/tabular.py:66, in TabularPreset.__init__(self, name, metadata, constraints)
     63     constraints = None
     65 if name == FAST_ML_PRESET:
---> 66     self._model = GaussianCopula(
     67         table_metadata=metadata,
     68         constraints=constraints,
     69         categorical_transformer='FrequencyEncoder_noised',
     70         default_distribution='gaussian',
     71         learn_rounding_scheme=False,
     72     )
     74     # Decide if transformers should model the null column or not.
     75     self._null_column = constraints is not None

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-bcde8fc9-f418-415d-b8c1-379e0fea2b65/lib/python3.9/site-packages/sdv/tabular/copulas.py:143, in GaussianCopula.__init__(self, field_names, field_types, field_transformers, anonymize_fields, primary_key, constraints, table_metadata, field_distributions, default_distribution, categorical_transformer, learn_rounding_scheme, enforce_min_max_values)
    136 def __init__(self, field_names=None, field_types=None, field_transformers=None,
    137              anonymize_fields=None, primary_key=None, constraints=None, table_metadata=None,
    138              field_distributions=None, default_distribution=None,
    139              categorical_transformer=None, learn_rounding_scheme=True,
    140              enforce_min_max_values=True):
    142     if isinstance(table_metadata, dict):
--> 143         table_metadata = Table.from_dict(table_metadata)
    145     if table_metadata:
    146         model_kwargs = table_metadata.get_model_kwargs(self.__class__.__name__)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-bcde8fc9-f418-415d-b8c1-379e0fea2b65/lib/python3.9/site-packages/sdv/metadata/table.py:812, in Table.from_dict(cls, metadata_dict, dtype_transformers)
    810 metadata_dict = copy.deepcopy(metadata_dict)
    811 fields = metadata_dict['fields'] or {}
--> 812 instance = cls(
    813     name=metadata_dict.get('name'),
    814     field_names=set(fields.keys()),
    815     field_types=fields,
    816     constraints=metadata_dict.get('constraints') or [],
    817     model_kwargs=metadata_dict.get('model_kwargs') or {},
    818     primary_key=metadata_dict.get('primary_key'),
    819     sequence_index=metadata_dict.get('sequence_index'),
    820     entity_columns=metadata_dict.get('entity_columns') or [],
    821     context_columns=metadata_dict.get('context_columns') or [],
    822     dtype_transformers=dtype_transformers,
    823     enforce_min_max_values=metadata_dict.get('enforce_min_max_values', True),
    824     learn_rounding_scheme=metadata_dict.get('learn_rounding_scheme', True),
    825 )
    826 instance._fields_metadata = fields
    827 return instance

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-bcde8fc9-f418-415d-b8c1-379e0fea2b65/lib/python3.9/site-packages/sdv/metadata/table.py:274, in Table.__init__(self, name, field_names, field_types, field_transformers, anonymize_fields, primary_key, constraints, dtype_transformers, model_kwargs, sequence_index, entity_columns, context_columns, learn_rounding_scheme, enforce_min_max_values)
    272 self._entity_columns = entity_columns or []
    273 self._context_columns = context_columns or []
--> 274 self._constraints = self._load_constraints(constraints)
    275 self._constraints_to_reverse = []
    276 self._dtype_transformers = self._DTYPE_TRANSFORMERS.copy()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-bcde8fc9-f418-415d-b8c1-379e0fea2b65/lib/python3.9/site-packages/sdv/metadata/table.py:252, in Table._load_constraints(constraints)
    250 for constraint in constraints:
    251     if isinstance(constraint, dict):
--> 252         loaded_constraints.append(Constraint.from_dict(constraint))
    253     else:
    254         loaded_constraints.append(constraint)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-bcde8fc9-f418-415d-b8c1-379e0fea2b65/lib/python3.9/site-packages/sdv/constraints/base.py:269, in Constraint.from_dict(cls, constraint_dict)
    267 if isinstance(constraint_class, str):
    268     if '.' in constraint_class:
--> 269         constraint_class = import_object(constraint_class)
    270     else:
    271         constraint_class = subclasses[constraint_class]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-bcde8fc9-f418-415d-b8c1-379e0fea2b65/lib/python3.9/site-packages/sdv/constraints/base.py:54, in import_object(obj)
     52 if isinstance(obj, str):
     53     package, name = obj.rsplit('.', 1)
---> 54     return getattr(importlib.import_module(package), name)
     56 return obj

AttributeError: module 'sdv.constraints.tabular' has no attribute 'CustomConstraint'
```

### Steps to reproduce

This is just a copy of the example given for custom constraints in the docs:

```
from sdv.demo import load_tabular_demo
from sdv.constraints import create_custom_constraint
from sdv.lite import TabularPreset

employees = load_tabular_demo()


def is_valid(column_names, data, increment, exclusion_column):
    column_name = column_names[0]
    is_divisible = data[column_name] % increment == 0
    is_excluded = data[exclusion_column] > 0
    return is_divisible | is_excluded


def transform(column_names, data, increment, exclusion_column):
    column_name = column_names[0]
    data[column_name] = data[column_name] / increment
    return data


def reverse_transform(column_names, transformed_data, increment, exclusion_column):
    column_name = column_names[0]
    is_included = transformed_data[exclusion_column] == 0
    rounded_data = transformed_data[is_included][column_name].round()
    transformed_data.at[is_included, column_name] = rounded_data
    transformed_data[column_name] *= increment
    return transformed_data


FixedIncrementsWithExclusion = create_custom_constraint(
    is_valid_fn=is_valid,
    transform_fn=transform,  # optional
    reverse_transform_fn=reverse_transform,  # optional
)

salary_divis_500 = FixedIncrementsWithExclusion(
    column_names=["salary"], increment=500, exclusion_column="contractor"
)

model = TabularPreset(constraints=[salary_divis_500], name='FAST_ML', metadata=metadata)
model.fit(data)
```

Inside `TabularPreset`, the constrain is represented in a dict as:

```
 'constraints': [{'constraint': 'sdv.constraints.tabular.CustomConstraint',
   'column_names': ['salary'],
   'increment': 500,
   'exclusion_column': 'contractor'}],
```

But that class is defined inside the `create_custom_constraint` function:
https://github.com/sdv-dev/SDV/blob/master/sdv/constraints/tabular.py#L88

Perhaps the class definition of `CustomConstraint` just needs to be at the top level?

**Comment by npatki** [comment] 2023-01-27 16:26
Hi @srowen,

Per the instructions in the [User Guide](https://sdv.dev/SDV/user_guides/single_table/custom_constraints.html#defining-your-custom-constraint), we recommend writing your custom constraint in a separate file.

For example you can create a new file called `custom_constraint.py`. All the code for validity check, transformations and creating your class should be in that file.

```python
from sdv.constraints import create_custom_constraint

def is_valid(...)
    # your code here

def transform(...)
    # your code here

def reverse_transform(...)
    # your code here

FixedIncrementsWithExclusion = create_custom_constraint(
    is_valid_fn=is_valid,
    transform_fn=transform,
    reverse_transform_fn=reverse_transform
)
```

Then, you can crate a _different_ file for making the model and fitting it. Assuming this is called `sdv_code.py`, the folder structure on your computer might look something like this:

```
Documents\
|--- sdv_code.py
|--- custom_constraint.py
```

In this case, the metadata should be as follows:
```python
 'constraints': [{'constraint': 'custom_constraint.FixedIncrementsWithExclusion',
   'column_names': ['salary'],
   'increment': 500,
   'exclusion_column': 'contractor'}],
```

**Comment by npatki** [comment] 2023-01-27 16:27
BTW I noticed an error in the custom constraint `reverse_transform` code that you may encounter on some versions of Python/numpy.

I recommend referring to #1197 to grab the updated code.

**Comment by srowen** [comment] 2023-01-27 16:38
OK fair enough. I wondered whether this can work without moving to another file, because I'd guess it's common to work in a notebook and inline this small section of code in a cell, not separate file, and it actually works great with other classes (TVAE, CTGAN), and I wondered if it were just a matter of moving that class definition.

**Comment by npatki** [comment] 2023-01-30 15:46
Hi @srowen good news is that these issues should be resolved in a future version of the SDV (dev is in progress).

> it actually works great with other classes (TVAE, CTGAN)

One issue right now is that the `constraints` can either be in the metadata or can be supplied separately to the model. I believe the `TabularPreset` is handling this logic differently than the other models -- but we are working to consolidated soon .

> I wondered whether this can work without moving to another file, because I'd guess it's common to work in a notebook and inline this small section of code in a cell, not separate file

I have filed #1205 to track this. (Note that the in-progress SDV version will have some API updates around the custom constraints part, so the code examples are slightly different to today.)

**Comment by npatki** [comment] 2023-01-30 17:42
Great! I'll resolve this as a duplicate of #1203.

> I'm preparing a post for the Databricks blog about SDV

Very cool! I'm sure the SDV team and community would be interested to read through your work -- I know I am. When it's published, feel free to share in our [Slack space](https://bit.ly/sdv-slack-invite) or via [Social media](https://twitter.com/sdv_dev).

**Closed** 2023-03-29 16:22 UTC
Labels: bug, resolution:duplicate, feature:constraints
