### ISSUE TITLE
Error occurs with FixedCombinations constraint when NA values exist in constraint column

### ISSUE THREAD

**Issue by jalr4ever** [sdv-dev/SDV#2168] opened 2024-08-05 02:20 UTC
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.14.0
* Python version: 3.11.9
* Operating System: macOS Sonoma 14.5 (M3 MAX)

### Error Description

When I add the FixedCombinations constraint and there are NA empty values in the constraint column, an error occurs. How can I resolve this situation?

For more detail, I found that the error occurred in `data_processor.py` 905 lines, `reversed_data[column_name] = reversed_data[column_name].astype(dtype)` , well, it's another `reverse_transform` function... not in the FixedCombinations ``reverse_transform()``It's happend when some line of the `column_name` is NA

```
Cannot convert non-finite values (NA or inf) to integer
```

### Steps to reproduce

Dataset's here: [stock_missingcol.csv](https://github.com/user-attachments/files/16489903/stock_missingcol.csv)

Replace the dataset, then run the code below: 

```python
from datetime import datetime

import pandas as pd
from sdv.evaluation.single_table import evaluate_quality, run_diagnostic
from sdv.metadata import SingleTableMetadata
from sdv.single_table import CTGANSynthesizer


constrains_column = ['Quantity', 'Total Price']


diagnose = False
export = True
file_name = '../datasets/stock_missingcol.csv'
current_time = datetime.now().strftime("%Y%m%d%H%M%S")
file_output_name = f'{file_name}_{current_time}_CTGAN_gen_synthetic.csv'

real_data = pd.read_csv(file_name)
print(f"Real data lines: {real_data.count()}")
print(real_data.head(10))

# Create metadata
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(real_data)

synthesizer = CTGANSynthesizer(
    metadata,
    epochs=2,
    verbose=True
)
synthesizer.load_custom_constraint_classes('OriginalFixedCombinations.py', class_names=['OriginalFixed'])
if all(column in real_data.columns for column in constrains_column):
    for column in constrains_column:
        if column in metadata.columns.keys():
            print(f"Column {column} update to categorical.")
            metadata.columns.get(column)['sdtype'] = 'categorical'
my_constraint = {
    'constraint_class': 'OriginalFixed',
    'constraint_parameters': {
        'column_names': constrains_column
    }
}
synthesizer.add_constraints([my_constraint])

synthesizer.fit(real_data)
# sample
synthetic_data = synthesizer.sample(num_rows=1000)
print(synthetic_data.head())
if export:
    synthetic_data.to_csv(file_output_name, index=False)
# evaluation
if diagnose:
    diagnostic = run_diagnostic(
        real_data=real_data,
        synthetic_data=synthetic_data,
        metadata=metadata
    )
    quality_report = evaluate_quality(
        real_data,
        synthetic_data,
        metadata
    )
    print(quality_report.get_details('Column Shapes'))

```

**Comment by srinify** [comment] 2024-08-12 20:44
Hi there @jalr4ever thanks for sharing your data, metadata, and code! I was able to reproduce the issue on my end using the FixedCombinations constraint. It looks like in your code, you load your own custom constraint class (from OriginalFixedCombinations.py) but your text suggests you were experimenting with FixedCombinations so I'm operating under that assumption

This looks like a bug after all, so thank you for helping us identify it. I *think* the issue may be happening specifically when the underlying values in the pandas dataframe are set to the `int ` dtype and the metadata is set to categorical. Then, SDV is failing in the reverse transform.

**Potential Workaround**

I was able to avoid this error by casting the `Total Price` from int -> float, then re-fitting, then sampling, then finally casting back to `int` in the sampled data. Do you mind trying that to see if that works for you?

```
# In real data, cast from int -> float
real_data['Total Price'] = real_data['Total Price'].astype(float)

# In synthetic data, cast from float -> int
synthetic_data['Total Price'] = synthetic_data['Total Price'].astype(int) 
```

**Comment by jalr4ever** [comment] 2024-08-13 01:53
> Hi there @jalr4ever thanks for sharing your data, metadata, and code! I was able to reproduce the issue on my end using the FixedCombinations constraint. It looks like in your code, you load your own custom constraint class (from OriginalFixedCombinations.py) but your text suggests you were experimenting with FixedCombinations so I'm operating under that assumption
> 
> This looks like a bug after all, so thank you for helping us identify it. I _think_ the issue may be happening specifically when the underlying values in the pandas dataframe are set to the `int ` dtype and the metadata is set to categorical. Then, SDV is failing in the reverse transform.
> 
> I opened this issue to reflect this bug: #2183
> 
> **Potential Workaround**
> 
> I was able to avoid this error by casting the `Total Price` from int -> float, then re-fitting, then sampling, then finally casting back to `int` in the sampled data. **Do you mind trying that to see if that works for you?** I'll keep this issue open until I hear back from you on this front!
> 
> ```
> # In real data, cast from int -> float
> real_data['Total Price'] = real_data['Total Price'].astype(float)
> 
> # In synthetic data, cast from float -> int
> synthetic_data['Total Price'] = synthetic_data['Total Price'].astype(int) 
> ```

Hi, @srinify . Your assumption was right. Never mind about `OriginalFixedCombinations.py`, since it's class logic total same as `FixedCombinations`. I tried your workaround code, it's work.

**Comment by srinify** [comment] 2024-08-13 20:08
Awesome @jalr4ever glad it worked for you too! I'll close this specific issue out then and we can track more development in the new bug issue: https://github.com/sdv-dev/SDV/issues/2183

Thanks again for raising this!

**Closed by srinify** 2024-08-13 20:08 UTC
Labels: bug, under discussion
