### ISSUE TITLE
PARSynthesizer creates limited ranges (and is unable to forecast past the max date)

### ISSUE THREAD

**Issue by Ng-ms** [sdv-dev/SDV#1752] opened 2024-01-23 22:37 UTC
**Problem Description:**

I am encountering an issue with the PARSynthesizer during the generation of synthetic data for medical records. Specifically, there seems to be an occurrence of date duplication in the synthetic dataset. The generated synthetic data exhibits repetition or limited variation in date values, even though the original dataset contains diverse date ranges from 2014 to 2023.

- Despite the varying start years and lengths of sequences, the PARSynthesizer does not seem to capture the full date range (2014 to 2023) for each patient.
- Date values in the synthetic data exhibit duplication or restricted variation.

How can we address the issue of date duplication in the synthetic data generated by the PARSynthesizer? Are there specific parameters or adjustments that should be considered to ensure accurate representation of the temporal aspects of the original dataset?

Any insights or recommendations on resolving this date duplication issue would be highly appreciated.

Thank you!

**Comment by npatki** [comment] 2024-01-24 21:27
Hi @Ng-ms, thanks for filing this issue. Generally, we keep 1 issue open per problem. I see that we already have an issue open for duplicate dates in the sequence index (in #1723), so let's continue to use the pre-existing issue to communicate. 

Let's **re-purpose the existing issue for the other problem of limited variation/creating the full range**. Ideally, PARSynthesizer should be able to create the full range of values, and even allow you to forecast past what you currently have. (I will update the title to reflect this.)

Unfortunately, this seems to be a quality issue, and I can't think of a quick fix or guaranteed workaround for it. You an always try updating the number of epochs to see if a longer training session would. Ultimately, the solution will require some more involved changes in the PAR algorithm. We can keep this issue open to track it, as well as communicate any updates or insights.

**Comment by npatki** [comment] 2024-01-26 20:42
Update on this: We have identified a root cause, which is now linked in #1760. You can follow that issue for an update.

Please note that this may not be the only root cause so until we resolve #1760, we will keep this one open.

**Comment by npatki** [comment] 2024-02-20 21:21
Hi @Ng-ms, this issue has now been resolved in the latest release (1.10.0). Please upgrade to see the newest functionality.

For your sequence index values, PARSynthesizer is now set up to learn:
1. The starting date of each sequence, and
2. The time intervals within each sequence

Using this information, it is designed to cover the full range of values that it observes from the real data.

### Forecasting
By default, the PARSynthesizer is set up to enforce the min/max dates that were in the real data. To allow forecasting past these dates, you can set the `enforce_min_max_values` parameter to `False` when creating your PAR synthesizer. Then you can request longer sequences to see the dates go into the future.

More information is available in the [demo notebook](https://colab.research.google.com/drive/1YLk2uwn8yrSRPy0soEeJwu8Hdk_tGTlE?usp=sharing). 

To see all available demos, [click here](https://docs.sdv.dev/sdv/demos)

**Closed by npatki** 2024-02-20 21:21 UTC
Labels: bug, under discussion

**Comment by npatki** [comment] 2024-02-21 14:01
Hi @Ng-ms -- sorry to hear. We can help debug. We typically will file 1 issue per problem. As this is a different problem now, could you file this in a new issue? Thanks.
